### Data Cleaning Practical Examples
#### Working With Columns Names

+ Get Random Dataset here https://www.generatedata.com/

#### Outline
    + How to check columns
    + How to rename columns
    + How to put underscore in all columns
    + How to replace a character or empty space in column names
    + How to uppercase/lowercase columns
    + How to select all columns except one
    + How to select columns of a particular order or phrase(df.filter)
    + How to select a group of column name

In [34]:
# Load Dataset
import pandas as pd

In [35]:
# Load Dataset
df = pd.read_csv("raw_dataset.csv")

In [36]:
# Firt Rows
df.head()

,First Name,Last name,Age,SALARY,STREET Address1,STREET Address2,STREET Address3,email
0,Joel,Padilla,10/28/2019,$92.32,"431-6530 Eu, Rd.",364-2264 Augue Rd.,"P.O. Box 864, 3882 Orci Street",eu@nibh.com
1,Fritz,Tyler,09/27/2019,$83.91,Ap #377-2267 Ac Av.,979-2228 Vel Ave,9865 Eu Av.,est.ac.mattis@malesuadafringilla.net
2,Wing,Phelps,02/18/2019,$17.15,Ap #545-5786 Pulvinar Ave,Ap #973-5781 Sagittis Avenue,9959 Ut St.,dolor@cubilia.net
3,Ryan,Ross,05/21/2019,$45.97,634-7858 Id Road,907-8824 Fringilla Ave,318-5271 In Ave,interdum.libero.dui@vitaeerat.com
4,Drake,Day,01/09/2020,$84.38,"999-8221 Tempor, St.",297-6939 Turpis. Ave,"P.O. Box 638, 6932 Laoreet Rd.",nulla.Integer.vulputate@liberoat.ca

In [37]:
# Columns
df.columns

Index(['First Name', 'Last name', 'Age', 'SALARY', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'email'],
      dtype='str')

In [38]:
## Features of Columns
dir(df.columns)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_arith_method',
 '_assert_can_do_setop',
 '_attributes',
 '_cache',
 '_can_hold_identifiers_and_holds_name',
 '_can_hold_na',
 '_can_hold_strings',
 '_can_use_libjoin',
 '_check_indexing_error',
 '_check_indexing_method',
 '_cleanup',
 '_cmp_method',
 '_comparables',
 '_concat',
 '_construct_result',
 '_constructor',
 '_convert_can_do_setop',
 '_convert_slice_indexer',
 '_convert_tolerance',
 '_data',
 '_data_cls',
 '_default_na_rep',
 '_difference',
 '_difference_compat',
 '_dir_additions',
 '_dir_additions_for_owner',
 '_dir_deletions',
 '_drop_level_numbers',
 '_dti_setop_align_tzs',
 '_dtype_to_subclass',
 '_duplicated',
 '_engine',
 '_engine_type',
 '_engine_types',
 '_ensure_array',
 '_filter_indexer_tolerance',
 '_find_common_type_compat',
 '_format_attrs',
 '_format_data',
 '_format_duplicate_message',
 '_format_flat',
 '_format_with_header',
 '_formatter_func',
 '_from_join_target',
 '_get_default_index_names',
 '_get_engine_target',
 '_get_fill_indexer',
 '_get_fill_indexer_searchsorted',
 '_get_indexer',
 '_get_indexer_non_comparable',
 '_get_indexer_strict',
 '_get_join_target',
 '_get_level_names',
 '_get_level_number',
 '_get_level_values',
 '_get_names',
 '_get_nearest_indexer',
 '_get_reconciled_name_object',
 '_get_string_slice',
 '_get_values_for_csv',
 '_getitem_slice',
 '_hidden_attrs',
 '_id',
 '_index_as_unique',
 '_inner_indexer',
 '_intersection',
 '_intersection_via_get_indexer',
 '_is_all_dates',
 '_is_comparable_dtype',
 '_is_memory_usage_qualified',
 '_is_multi',
 '_is_strictly_monotonic_decreasing',
 '_is_strictly_monotonic_increasing',
 '_isnan',
 '_join_empty',
 '_join_level',
 '_join_monotonic',
 '_join_multi',
 '_join_non_unique',
 '_join_via_get_indexer',
 '_left_indexer',
 '_left_indexer_unique',
 '_logical_method',
 '_map_values',
 '_maybe_cast_indexer',
 '_maybe_cast_listlike_indexer',
 '_maybe_cast_slice_bound',
 '_maybe_check_unique',
 '_maybe_copy_array_input',
 '_maybe_disable_logical_methods',
 '_maybe_disallow_fill',
 '_maybe_downcast_for_indexing',
 '_maybe_preserve_names',
 '_memory_usage',
 '_module_source',
 '_mpl_repr',
 '_na_value',
 '_name',
 '_no_setting_name',
 '_outer_indexer',
 '_raise_if_missing',
 '_raise_invalid_indexer',
 '_raise_scalar_data_error',
 '_references',
 '_reindex_non_unique',
 '_rename',
 '_requires_unique_msg',
 '_reset_cache',
 '_reset_identity',
 '_searchsorted_monotonic',
 '_set_names',
 '_shallow_copy',
 '_should_compare',
 '_should_fallback_to_positional',
 '_should_partial_index',
 '_simple_new',
 '_sort_levels_monotonic',
 '_summary',
 '_supports_partial_string_indexing',
 '_transform_index',
 '_typ',
 '_unary_method',
 '_union',
 '_validate_can_reindex',
 '_validate_fill_value',
 '_validate_index_level',
 '_validate_indexer',
 '_validate_names',
 '_validate_positional_slice',
 '_validate_sort_keyword',
 '_values',
 '_view',
 '_with_infer',
 '_wrap_difference_result',
 '_wrap_intersection_result',
 '_wrap_join_result',
 '_wrap_reindex_result',
 '_wrap_setop_result',
 'all',
 'any',
 'append',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asof',
 'asof_locs',
 'astype',
 'copy',
 'delete',
 'diff',
 'difference',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'duplicated',
 'empty',
 'equals',
 'factorize',
 'fillna',
 'get_indexer',
 'get_indexer_for',
 'get_indexer_non_unique',
 'get_level_values',
 'get_loc',
 'get_slice_bound',
 'groupby',
 'has_duplicates',
 'hasnans',
 'identical',
 'infer_objects',
 'inferred_type',
 'insert',
 'intersection',
 'is_',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'join',
 'map',
 'max',
 'memory_usage',
 'min',
 'name',
 'names',
 'nbytes',
 'ndim',
 'nlevels',
 'notna',
 'notnull',
 'nunique',
 'putmask',
 'ravel',
 'reindex',
 'rename',
 'repeat',
 'round',
 'searchsorted',
 'set_names',
 'shape',
 'shift',
 'size',
 'slice_indexer',
 'slice_locs',
 'sort_values',
 'sortlevel',
 'str',
 'symmetric_difference',
 'take',
 'to_flat_index',
 'to_frame',
 'to_list',
 'to_numpy',
 'to_series',
 'transpose',
 'union',
 'unique',
 'value_counts',
 'values',
 'view',
 'where']

In [39]:
### Get The Columns As an Array
df.columns.values

<StringArray>
[     'First Name',       'Last name',             'Age',          'SALARY',
 'STREET Address1', 'STREET Address2', 'STREET Address3',           'email']
Length: 8, dtype: str

In [40]:
### Get The Columns As  List
df.columns.tolist()

['First Name',
 'Last name',
 'Age',
 'SALARY',
 'STREET Address1',
 'STREET Address2',
 'STREET Address3',
 'email']

In [41]:
### To View Columns Names
df.columns.view()

Index(['First Name', 'Last name', 'Age', 'SALARY', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'email'],
      dtype='str')

In [42]:
# Convert the Column Names To Series/ DataFrame
df.columns.to_series()

First Name              First Name
Last name                Last name
Age                            Age
SALARY                      SALARY
STREET Address1    STREET Address1
STREET Address2    STREET Address2
STREET Address3    STREET Address3
email                        email
dtype: str

In [43]:
# Convert the Column Names To DataFrame
df.columns.to_frame()

                               0
First Name            First Name
Last name              Last name
Age                          Age
SALARY                    SALARY
STREET Address1  STREET Address1
STREET Address2  STREET Address2
STREET Address3  STREET Address3
email                      email

In [44]:
# Check to see if column names contains a phrase
df.columns.str.contains('Age')

array([False, False,  True, False, False, False, False, False])

In [45]:
# Check to see if column names contains a phrase
'Age' in df.columns

True

In [46]:
# Check to see if column names are duplicated
df.columns.duplicated()

array([False, False, False, False, False, False, False, False])

In [47]:
### Attributes and Methods of Str
dir(df.columns.str)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'match',
 'normalize',
 'pad',
 'partition',
 'removeprefix',
 'removesuffix',
 'repeat',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'slice',
 'slice_replace',
 'split',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'wrap',
 'zfill']

In [48]:
### Making Column Name Lower Case
df.columns.str.lower()

Index(['first name', 'last name', 'age', 'salary', 'street address1',
       'street address2', 'street address3', 'email'],
      dtype='str')

In [49]:
### Making Column Name Upper Case
df.columns.str.upper()

Index(['FIRST NAME', 'LAST NAME', 'AGE', 'SALARY', 'STREET ADDRESS1',
       'STREET ADDRESS2', 'STREET ADDRESS3', 'EMAIL'],
      dtype='str')

In [50]:
### Making Column Name Title Case
df.columns.str.title()

Index(['First Name', 'Last Name', 'Age', 'Salary', 'Street Address1',
       'Street Address2', 'Street Address3', 'Email'],
      dtype='str')

In [51]:
### Replacing Empty spaces with underscore
df.columns.str.replace(' ','_')

Index(['First_Name', 'Last_name', 'Age', 'SALARY', 'STREET_Address1',
       'STREET_Address2', 'STREET_Address3', 'email'],
      dtype='str')

In [52]:
### Renaming Column Name
df.rename(columns={'Age':'Date of Birth'})

,First Name,Last name,Date of Birth,SALARY,STREET Address1,STREET Address2,STREET Address3,email
0,Joel,Padilla,10/28/2019,$92.32,"431-6530 Eu, Rd.",364-2264 Augue Rd.,"P.O. Box 864, 3882 Orci Street",eu@nibh.com
1,Fritz,Tyler,09/27/2019,$83.91,Ap #377-2267 Ac Av.,979-2228 Vel Ave,9865 Eu Av.,est.ac.mattis@malesuadafringilla.net
2,Wing,Phelps,02/18/2019,$17.15,Ap #545-5786 Pulvinar Ave,Ap #973-5781 Sagittis Avenue,9959 Ut St.,dolor@cubilia.net
3,Ryan,Ross,05/21/2019,$45.97,634-7858 Id Road,907-8824 Fringilla Ave,318-5271 In Ave,interdum.libero.dui@vitaeerat.com
4,Drake,Day,01/09/2020,$84.38,"999-8221 Tempor, St.",297-6939 Turpis. Ave,"P.O. Box 638, 6932 Laoreet Rd.",nulla.Integer.vulputate@liberoat.ca
...,...,...,...,...,...,...,...,...
95,Victor,Hobbs,05/24/2019,$54.56,4034 Vitae St.,"P.O. Box 930, 1683 Eu Rd.","P.O. Box 181, 3360 Mus. Rd.",ipsum@dictumaugue.com
96,Neil,Bradford,02/07/2020,$74.52,"1434 Aliquet, Street",956-6627 Nunc Av.,Ap #727-6109 Sapien. Av.,sapien.Nunc@euodioPhasellus.net
97,Noble,Conrad,10/29/2019,$43.99,"Ap #173-7049 Eget, St.",Ap #620-2512 Ut Street,8768 Aenean St.,tellus.Nunc.lectus@ornare.org
98,Brody,Whitaker,08/09/2018,$96.24,Ap #371-9803 Aliquam Rd.,8892 Euismod Street,Ap #201-659 Libero. Street,non.dapibus.rutrum@eumetus.co.uk
99,Alden,Mccormick,07/27/2019,$2.66,Ap #375-1139 Risus. Road,7259 Duis Avenue,955-4058 Maecenas St.,ut.erat@aceleifend.com

In [53]:
### Renaming Column Name /Inplace
df.rename(columns={'Age':'Date of Birth'},inplace=True)

In [54]:
df.columns

Index(['First Name', 'Last name', 'Date of Birth', 'SALARY', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'email'],
      dtype='str')

In [55]:
len(df.columns.values)

8

In [56]:
# Renaming Column Names using select values
df.columns.values[7] = 'Email Address'

In [57]:
df.columns

Index(['First Name', 'Last name', 'Date of Birth', 'SALARY', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'Email Address'],
      dtype='str')

In [58]:
### Selecting All Columns Except One
df.columns[df.columns != 'SALARY']

Index(['First Name', 'Last name', 'Date of Birth', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'Email Address'],
      dtype='str')

In [59]:
### Selecting All Columns Except One
df.loc[:, df.columns != 'SALARY'].columns

Index(['First Name', 'Last name', 'Date of Birth', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'Email Address'],
      dtype='str')

In [60]:
# Select Column Names Except One Using Difference
df.columns.difference(['SALARY'])

Index(['Date of Birth', 'Email Address', 'First Name', 'Last name',
       'STREET Address1', 'STREET Address2', 'STREET Address3'],
      dtype='str')

In [61]:
# Select Column Names Except One Using Negation of isin
df.loc[:,~df.columns.isin(['SALARY'])].columns

Index(['First Name', 'Last name', 'Date of Birth', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'Email Address'],
      dtype='str')

In [62]:
### Select Column Names that Begins with a Word or Character
df.filter(like='STREET').columns

Index(['STREET Address1', 'STREET Address2', 'STREET Address3'], dtype='str')

In [63]:
### Select Column Names that Begins with a Word or Character
df.loc[:,df.columns.str.startswith('STREET')].columns

Index(['STREET Address1', 'STREET Address2', 'STREET Address3'], dtype='str')

In [64]:
### Select Column Names that ENDS with a Word or Character
df.loc[:,df.columns.str.endswith('ame')].columns

Index(['First Name', 'Last name'], dtype='str')

In [65]:
### Select Column Names that ENDS with a Word or Character Using Filter and Regex name$
df.filter(regex='ame$',axis=1).columns

Index(['First Name', 'Last name'], dtype='str')

In [66]:
### Select A Group of Column Names
df.columns.values[0:4]

<StringArray>
['First Name', 'Last name', 'Date of Birth', 'SALARY']
Length: 4, dtype: str

In [67]:
### Select A Group of Column Names
df.columns[0:4]

Index(['First Name', 'Last name', 'Date of Birth', 'SALARY'], dtype='str')

In [68]:
### Thanks For Watching
## Jesus Saves@JCharisTech 
## Jesse E. Agbe(JCharis)
## J-Secur1ty