
# Introdução ao Pandas

O Pandas, assim como o Numpy, é central na aplicação de Data Science com o Python. Essa biblioteca extende as capacidades das matrizes do Numpy para uma estrutura mais familiar da análise de dados, o <i>dataframe</i> (conjunto de dados com linhas e colunas nominais). Veremos nessa seção como ler os dados de seu estudo, como manipular esses dados usando as principais funcionalidades do Pandas e, por fim, como exportar o resultado para compartilhamento futuro.

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRXCDD7q7wCVdRNtROzgtARnDThPmab6k2x7Q&usqp=CAU">

## Os principais tipos de estrutura do Pandas: Series e Dataframe.

### O objeto Series

Uma "série" do Pandas nada mais é do que uma matriz de N linhas e 1 (uma) coluna. Veja:

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /home/weder/Documentos/Projects/PyCodeData2025/.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /home/weder/Documentos/Projects/PyCodeData2025/.venv/lib/python3.12/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/weder/Documentos/Projects/PyCodeData2025/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/weder/Documentos/Projects/PyCodeData2025/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/weder/Documentos/Projects/PyCodeData2025/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/weder/Documentos/Projects/PyCodeData2025/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [1]:
import pandas as pd # Essa é a convenção para importar o Pandas

In [58]:
serie = pd.Series([10,20,30,40,50])
serie

0    10
1    20
2    30
3    40
4    50
dtype: int64

Como vemos acima, uma série do Pandas é um conjunto de dados (a matriz) e seu índice (valores de 0 a 4 no exemplo).

In [59]:
serie.values

array([10, 20, 30, 40, 50])

In [4]:
serie.index

RangeIndex(start=0, stop=5, step=1)

Podemos inclusive mudar os índices da série por strings. Veja:

In [5]:
serie = pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
serie

a    10
b    20
c    30
d    40
e    50
dtype: int64

Assim com as matrizes do Numpy, podemos acessar elementos da série usando seus índices. Veja:

In [6]:
serie['c']

np.int64(30)

In [7]:
serie[['c','a']]

c    30
a    10
dtype: int64

In [8]:
serie[1:3]

b    20
c    30
dtype: int64

Podemos construir séries do Pandas usando matrizes do Numpy. Veja:

In [9]:
import numpy as np
linha = np.random.random(10)
linha

array([0.72768059, 0.68448314, 0.77160171, 0.07920981, 0.20634806,
       0.84521017, 0.72035807, 0.64719064, 0.37844712, 0.16644869])

In [10]:
serie2 = pd.Series(linha)
serie2

0    0.727681
1    0.684483
2    0.771602
3    0.079210
4    0.206348
5    0.845210
6    0.720358
7    0.647191
8    0.378447
9    0.166449
dtype: float64

### O objeto DataFrame

Um "DataFrame" do Pandas nada mais é do que uma matriz de N linhas e M colunas. Além disso, podemos pensar no DataFrame como um conjunto de séries do Pandas em conjunto. Veja:

In [11]:
serie1 = pd.Series(np.random.random(10))
serie2 = pd.Series(np.random.randint(1,10,10))

In [12]:
df = pd.DataFrame( {'coluna1': serie1,'coluna2': serie2} ) # Passamos um dicionário de séries para o DataFrame
df # df é um nome comum em Data Science para DataFrame

    coluna1  coluna2
0  0.669926        2
1  0.819403        9
2  0.449004        3
3  0.562479        4
4  0.664721        1
5  0.714376        7
6  0.828556        7
7  0.204766        6
8  0.749667        2
9  0.150017        4

In [13]:
df.values

array([[0.66992582, 2.        ],
       [0.81940345, 9.        ],
       [0.44900404, 3.        ],
       [0.56247941, 4.        ],
       [0.66472076, 1.        ],
       [0.7143762 , 7.        ],
       [0.82855617, 7.        ],
       [0.20476626, 6.        ],
       [0.74966663, 2.        ],
       [0.15001664, 4.        ]])

In [14]:
df.index

RangeIndex(start=0, stop=10, step=1)

# Acessando elementos do DataFrame

Assim como as matrizes do Numpy, as séries e dataframes do Pandas possibilitam que acessemos os elementos com operações dos índices e filtros usando operadore de comparação. Veja alguns exemplos:

In [15]:
df

    coluna1  coluna2
0  0.669926        2
1  0.819403        9
2  0.449004        3
3  0.562479        4
4  0.664721        1
5  0.714376        7
6  0.828556        7
7  0.204766        6
8  0.749667        2
9  0.150017        4

In [16]:
# Acessando as primeiras 3 linhas
df[0:3]

    coluna1  coluna2
0  0.669926        2
1  0.819403        9
2  0.449004        3

<b>Dica:</b> Um método do Pandas muito comum para ver as primeiras linhas de um DataFrame é o método .head(). Veja:

In [17]:
df.head()

    coluna1  coluna2
0  0.669926        2
1  0.819403        9
2  0.449004        3
3  0.562479        4
4  0.664721        1

In [18]:
df.head(10)

    coluna1  coluna2
0  0.669926        2
1  0.819403        9
2  0.449004        3
3  0.562479        4
4  0.664721        1
5  0.714376        7
6  0.828556        7
7  0.204766        6
8  0.749667        2
9  0.150017        4

Dá mesma forma que temos o .head() para ver as primeiras linhas, temos o .tail() para ver as últimas. Veja:

In [19]:
df.tail(3)

    coluna1  coluna2
7  0.204766        6
8  0.749667        2
9  0.150017        4

In [20]:
# Acessando a segunda coluna
df[['coluna2']]

   coluna2
0        2
1        9
2        3
3        4
4        1
5        7
6        7
7        6
8        2
9        4

In [21]:
# Acessando a segunda coluna e as 3 primeiras linhas
df[['coluna2']][:3]

   coluna2
0        2
1        9
2        3

In [22]:
# Acessando apenas as linhas em que a "coluna1" for maior que 0.5

In [23]:
df['coluna1'] > 0.5

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
8     True
9    False
Name: coluna1, dtype: bool

In [24]:
df[ df['coluna1'] > 0.5 ]

    coluna1  coluna2
0  0.669926        2
1  0.819403        9
3  0.562479        4
4  0.664721        1
5  0.714376        7
6  0.828556        7
8  0.749667        2

In [25]:
# Acessando apenas as linhas em que a "coluna1" for maior que 0.5 E a "coluna2" for maior que 8

In [26]:
df[ (df['coluna1'] > 0.5) & (df['coluna2'] > 8) ]

    coluna1  coluna2
1  0.819403        9

## Acessando índices específicos com os métodos .loc e .iloc

In [27]:
df

    coluna1  coluna2
0  0.669926        2
1  0.819403        9
2  0.449004        3
3  0.562479        4
4  0.664721        1
5  0.714376        7
6  0.828556        7
7  0.204766        6
8  0.749667        2
9  0.150017        4

In [28]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [29]:
df = df.T # O método T aplica a transformação transposta a uma matriz

In [30]:
df

,0,1,2,3,4,5,6,7,8,9
coluna1,0.669926,0.819403,0.449004,0.562479,0.664721,0.714376,0.828556,0.204766,0.749667,0.150017
coluna2,2.000000,9.000000,3.000000,4.000000,1.000000,7.000000,7.000000,6.000000,2.000000,4.000000

In [31]:
df.index

Index(['coluna1', 'coluna2'], dtype='object')

In [32]:
df.loc['coluna2'] # O método .loc busca o índices de string. Ex: "coluna1"

0    2.0
1    9.0
2    3.0
3    4.0
4    1.0
5    7.0
6    7.0
7    6.0
8    2.0
9    4.0
Name: coluna2, dtype: float64

In [33]:
df.iloc[1] # O método .iloc busca o índices numéricos (o i vem de integer). Ex: 0.

0    2.0
1    9.0
2    3.0
3    4.0
4    1.0
5    7.0
6    7.0
7    6.0
8    2.0
9    4.0
Name: coluna2, dtype: float64

In [34]:
df.loc['coluna2']

0    2.0
1    9.0
2    3.0
3    4.0
4    1.0
5    7.0
6    7.0
7    6.0
8    2.0
9    4.0
Name: coluna2, dtype: float64

In [35]:
df.iloc[1]

0    2.0
1    9.0
2    3.0
3    4.0
4    1.0
5    7.0
6    7.0
7    6.0
8    2.0
9    4.0
Name: coluna2, dtype: float64

In [36]:
df

,0,1,2,3,4,5,6,7,8,9
coluna1,0.669926,0.819403,0.449004,0.562479,0.664721,0.714376,0.828556,0.204766,0.749667,0.150017
coluna2,2.000000,9.000000,3.000000,4.000000,1.000000,7.000000,7.000000,6.000000,2.000000,4.000000

In [37]:
df.iloc[1:,-2:] # Acessa o DataFrame a partir da linha de índice 1 e as últimas 2 colunas (-2)

           8    9
coluna2  2.0  4.0

# Juntando dados de diferentes DataFrames

Uma operação muito comum em manipulação de dados é a junção de diferentes DataFrames. Nesta seção vamos falar sobre essas operações, começando com a Concatenação e finalizando com os Merges e Joins de tabelas.

## Leitura e Escrita de bases externas

In [38]:
df = pd.read_csv("../datasets/base.csv")

In [39]:
df # Perceba que as colunas não foram importadas corretamente

      A;B;C
0  A0;B0;C0
1  A1;B1;C1
2  A2;B2;C2
3  A3;B3;C3
4  A4;B4;C4

In [40]:
df = pd.read_csv("../datasets/base.csv", sep=";")

In [41]:
df

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4

In [42]:
# Para escrever em disco um arquivo CSV, basta usar o método .to_csv()
df.to_csv("../datasets/base_final.csv",sep=";")

## Concatenação

In [43]:
df

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4

In [44]:
df1 = df.iloc[:2]
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1

In [45]:
df2 = df.iloc[2:]
df2

    A   B   C
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4

In [46]:
# concatena os dois dataframes com o método .concat()

In [47]:
df3 = pd.concat((df1,df2))
df3

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4

## Merges e Joins

Pra quem já usou bancos de dados relacionais como o SQL já deve conhecer o JOIN de tabelas. Usuários de Microsoft Excel devem entender os JOIN's como o resultados de funções de procura como o PROCV. No Pandas, conseguimos performar essas mesmas operações usando o método .merge().

Em SQL, temos representações dos JOIN's conforme abaixo:
<br>
<img src="https://s3-sa-east-1.amazonaws.com/preditiva.ai/diversos/sql_join.jpg">

<br>
Vamos entender como fazer essas operações no Pandas:

In [48]:
df1 = pd.DataFrame({'aluno': ['Joao','Maria','Helena','Joel','Gabriel'],
                    'idade': [30,25,18,29,45]})
df1

     aluno  idade
0     Joao     30
1    Maria     25
2   Helena     18
3     Joel     29
4  Gabriel     45

In [49]:
df2 = pd.DataFrame({'nome': ['Joao','Maria','Helena','Joel','Gabriel'],
                    'altura': [1.60,1.70,1.80,1.90,2.00]})
df2

      nome  altura
0     Joao     1.6
1    Maria     1.7
2   Helena     1.8
3     Joel     1.9
4  Gabriel     2.0

In [50]:
# Se quisermos juntar as informações de nome, idade e altura, precisamos usar o .merge() do Pandas da seguinte forma:
df3 = pd.merge(df1,df2,how='left',left_on='aluno',right_on='nome')
df3

     aluno  idade     nome  altura
0     Joao     30     Joao     1.6
1    Maria     25    Maria     1.7
2   Helena     18   Helena     1.8
3     Joel     29     Joel     1.9
4  Gabriel     45  Gabriel     2.0

In [51]:
# podemos remover um dos campos de nome com o comando .drop(). Veja:
df3 = pd.merge(df1,df2,how='left',left_on='aluno',right_on='nome').drop('nome',axis=1) # o axis = 1 representa uma coluna
df3

     aluno  idade  altura
0     Joao     30     1.6
1    Maria     25     1.7
2   Helena     18     1.8
3     Joel     29     1.9
4  Gabriel     45     2.0

O parâmetro "how" define o tipo de Join (no estilo SQL como vimos na figura acima) que queremos fazer. Veja um resumo abaixo:
<br><br>
<img src="https://s3-sa-east-1.amazonaws.com/preditiva.ai/diversos/pandas_merge.png">

In [52]:
# Vejamos um exemplo de Inner (quando queremos apenas unir as tabelas cujos elementos sejam iguais)
df1

     aluno  idade
0     Joao     30
1    Maria     25
2   Helena     18
3     Joel     29
4  Gabriel     45

In [53]:
df4 = pd.DataFrame({'nome': ['Joel','Gabriel'],
                    'altura': [1.60,1.70]})
df4

      nome  altura
0     Joel     1.6
1  Gabriel     1.7

In [54]:
df5 = pd.merge(df1,df4,how='inner',left_on='aluno',right_on='nome').drop('nome',axis=1) # o axis = 1 representa uma coluna
df5

     aluno  idade  altura
0     Joel     29     1.6
1  Gabriel     45     1.7

Veja que apenas os alunos Joel e Gabriel existem nas duas tabelas. O <b>inner join</b> traz apenas esses elementos.

In [55]:
df.lo

AttributeError: 'DataFrame' object has no attribute 'lo'

In [ ]:
# Veja se fizéssemos um left join em um caso como esse:
df6 = pd.merge(df1,df4,how='left',left_on='aluno',right_on='nome').drop('nome',axis=1) # o axis = 1 representa uma coluna
df6

     aluno  idade  altura
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7

In [ ]:
df6.mean()

idade     29.40
altura     1.65
dtype: float64

Como a tabela "right" (no caso, o df4) só tem informações para Joel e Gabriel, os outros alunos ficam sem informação e o Pandas atribui um tipo de dado chamado <b>NaN</b> (um tipo de dado faltante, isto é, um dado <i>missing</i>). Veremos como tratar dados missing nas próximas seções.

# Agregando dados no Pandas

Assim como fizemos no Numpy, o Pandas tem uma série de funções de agregação como `sum(), mean(), median(), min(), max()` e etc. Essa funções ajudam muito quando precisamos resumir variáveis em um dataframe. Vejamos como essas agregações funcionam:

In [ ]:
# Vamos usar o pacote Seaborn para carregar um dataframe
import seaborn as sns
df = sns.load_dataset('flights')

In [ ]:
df.head()

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [ ]:
df.shape

(144, 3)

In [ ]:
df.tail()

     year      month  passengers
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [ ]:
df.dtypes

year             int64
month         category
passengers       int64
dtype: object

In [ ]:
# O primeiro método de agregação muito simples é o .describe() . Veja o resultado:
df.describe()

              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000

Além disso, poderíamos extrair esses dados de forma individual usando as funções de agregação diretamente.

In [ ]:
df.mean()

year          1954.500000
passengers     280.298611
dtype: float64

In [ ]:
df.median()

year          1954.5
passengers     265.5
dtype: float64

In [ ]:
df[ df['year'] == 1958 ]

     year      month  passengers
108  1958    January         340
109  1958   February         318
110  1958      March         362
111  1958      April         348
112  1958        May         363
113  1958       June         435
114  1958       July         491
115  1958     August         505
116  1958  September         404
117  1958    October         359
118  1958   November         310
119  1958   December         337

In [ ]:
# Se quiséssemos extrair a média de passageiros de um determinado ano ? Ex: 1958 ?
df[ df['year'] == 1958 ].mean()

year          1958.0
passengers     381.0
dtype: float64

Deve ter um jeito mais fácil de aplicar a média em cada ano diretamente sem realizar filtros como fizemos acima. <b>Apresentamos o método GroupBy !!!</b>

## O método GroupBy

O método GroupBy realiza o comportamento análogo ao comando GROUP BY do SQL. Esse método possibilita aplicarmos funções de agregação a um conjunto de valores de uma variável individualmente. Veja o exemplo abaixo:

In [ ]:
# Média de passageiros por ano
df.groupby('year').agg({'passengers': 'mean'})

      passengers
year
1949  126.666667
1950  139.666667
1951  170.166667
1952  197.000000
1953  225.000000
1954  238.916667
1955  284.000000
1956  328.250000
1957  368.416667
1958  381.000000
1959  428.333333
1960  476.166667

In [ ]:
pd.set_option('display.max_rows', 500)

# Média de passageiros por mês
df.groupby(['year','month']).agg({'passengers': 'mean'})

                passengers
year month
1949 January           112
     February          118
     March             132
     April             129
     May               121
     June              135
     July              148
     August            148
     September         136
     October           119
     November          104
     December          118
1950 January           115
     February          126
     March             141
     April             135
     May               125
     June              149
     July              170
     August            170
     September         158
     October           133
     November          114
     December          140
1951 January           145
     February          150
     March             178
     April             163
     May               172
     June              178
     July              199
     August            199
     September         184
     October           162
     November          146
     December          166
1952 January           171
     February          180
     March             193
     April             181
     May               183
     June              218
     July              230
     August            242
     September         209
     October           191
     November          172
     December          194
1953 January           196
     February          196
     March             236
     April             235
     May               229
     June              243
     July              264
     August            272
     September         237
     October           211
     November          180
     December          201
1954 January           204
     February          188
     March             235
     April             227
     May               234
     June              264
     July              302
     August            293
     September         259
     October           229
     November          203
     December          229
1955 January           242
     February          233
     March             267
     April             269
     May               270
     June              315
     July              364
     August            347
     September         312
     October           274
     November          237
     December          278
1956 January           284
     February          277
     March             317
     April             313
     May               318
     June              374
     July              413
     August            405
     September         355
     October           306
     November          271
     December          306
1957 January           315
     February          301
     March             356
     April             348
     May               355
     June              422
     July              465
     August            467
     September         404
     October           347
     November          305
     December          336
1958 January           340
     February          318
     March             362
     April             348
     May               363
     June              435
     July              491
     August            505
     September         404
     October           359
     November          310
     December          337
1959 January           360
     February          342
     March             406
     April             396
     May               420
     June              472
     July              548
     August            559
     September         463
     October           407
     November          362
     December          405
1960 January           417
     February          391
     March             419
     April             461
     May               472
     June              535
     July              622
     August            606
     September         508
     October           461
     November          390
     December          432

In [ ]:
# Média e máximo de passageiros por mês
df.groupby('month').agg({'passengers': ['mean','max','std'] })

           passengers
                 mean  max         std
month
January    241.750000  417  101.032960
February   235.000000  391   89.619397
March      270.166667  419  100.559194
April      267.083333  461  107.374839
May        271.833333  472  114.739890
June       311.666667  535  134.219856
July       351.333333  622  156.827255
August     351.083333  606  155.783333
September  302.416667  508  123.954140
October    266.583333  461  110.744964
November   232.833333  390   95.185783
December   261.833333  432  103.093808

In [ ]:
# Podemos ter todas as principais medidas com o describe()
df.groupby('month')['passengers'].describe()

           count        mean         std    min     25%    50%     75%    max
month
January     12.0  241.750000  101.032960  112.0  164.50  223.0  321.25  417.0
February    12.0  235.000000   89.619397  118.0  172.50  214.5  305.25  391.0
March       12.0  270.166667  100.559194  132.0  189.25  251.5  357.50  419.0
April       12.0  267.083333  107.374839  129.0  176.50  252.0  348.00  461.0
May         12.0  271.833333  114.739890  121.0  180.25  252.0  357.00  472.0
June        12.0  311.666667  134.219856  135.0  208.00  289.5  425.25  535.0
July        12.0  351.333333  156.827255  148.0  222.25  333.0  471.50  622.0
August      12.0  351.083333  155.783333  148.0  231.25  320.0  476.50  606.0
September   12.0  302.416667  123.954140  136.0  202.75  285.5  404.00  508.0
October     12.0  266.583333  110.744964  119.0  183.75  251.5  350.00  461.0
November    12.0  232.833333   95.185783  104.0  165.50  220.0  306.25  390.0
December    12.0  261.833333  103.093808  118.0  187.00  253.5  336.25  432.0

## O método PivotTable

Outro método interessante para fazer agregações é o PivotTables. Pense nesse método como uma Tabela Dinâmica (Pivot Tables) do Microsoft Excel. Com ela, podemos fazer agregações como fizemos com o GroupBy, porém para mais de uma variável simultaneamente. Veja exemplos abaixo:

In [ ]:
# Média de passageiros por ano e mês
df.pivot_table(index='year',columns='month',aggfunc={'passengers': 'mean'})

      passengers                                                               \
month    January February March April  May June July August September October
year
1949         112      118   132   129  121  135  148    148       136     119
1950         115      126   141   135  125  149  170    170       158     133
1951         145      150   178   163  172  178  199    199       184     162
1952         171      180   193   181  183  218  230    242       209     191
1953         196      196   236   235  229  243  264    272       237     211
1954         204      188   235   227  234  264  302    293       259     229
1955         242      233   267   269  270  315  364    347       312     274
1956         284      277   317   313  318  374  413    405       355     306
1957         315      301   356   348  355  422  465    467       404     347
1958         340      318   362   348  363  435  491    505       404     359
1959         360      342   406   396  420  472  548    559       463     407
1960         417      391   419   461  472  535  622    606       508     461


month November December
year
1949       104      118
1950       114      140
1951       146      166
1952       172      194
1953       180      201
1954       203      229
1955       237      278
1956       271      306
1957       305      336
1958       310      337
1959       362      405
1960       390      432

# Outras manipulações importantes

## Dados missing

Algo comum em manipulação de dados é lidar com dados missing. O Pandas fornece uma série de métodos para lidar com esses problemas em dataframes. Veja a seguir:

In [ ]:
df1

     aluno  idade
0     Joao     30
1    Maria     25
2   Helena     18
3     Joel     29
4  Gabriel     45

In [ ]:
df4

      nome  altura
0     Joel     1.6
1  Gabriel     1.7

In [ ]:
# Como vimos em seções anteriores, o merge abaixo produziu dados missing (NaN) pois a tabela "right" não tinha a altura para os 3 primeiros alunos.
df = pd.merge(df1,df4,how='left',left_on='aluno',right_on='nome').drop('nome',axis=1) # o axis = 1 representa uma coluna
df

     aluno  idade  altura
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7

Sempre que lidamos com um dataframe novo é muito importante detectar se temos dados missing. Podemos fazer isso da seguinte forma:

In [ ]:
df.isna()

   aluno  idade  altura
0  False  False    True
1  False  False    True
2  False  False    True
3  False  False   False
4  False  False   False

In [ ]:
df.isna().sum() # a variável altura tem 3 linhas com missing

aluno     0
idade     0
altura    3
dtype: int64

Agora que detectamos, precisamos decidir o que fazer com os dados missing. Em determinadas situações, os missings não servem para nada e podemos <b>excluí-los</b>. Veja:

In [ ]:
df.dropna()

     aluno  idade  altura
3     Joel     29     1.6
4  Gabriel     45     1.7

Mas a operação acima foi muito drástica, pois perdemos a informação da linha inteira dos 3 primeiros alunos. Neste caso vale mais a pena excluir apenas a coluna com mais missings (ou seja, a coluna altura).

In [ ]:
df.dropna(axis='columns')

     aluno  idade
0     Joao     30
1    Maria     25
2   Helena     18
3     Joel     29
4  Gabriel     45

Mas é possível argumentar que também perdemos a informação dos ultimos alunos. E se excluirmos apenas as colunas que tiverem um determinado número de missings?

In [ ]:
df.dropna(axis='columns',thresh=2) # esse parametro só exclui colunas com um minimo de 2 valores não missing

     aluno  idade  altura
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7

In [ ]:
df.dropna(axis='columns',thresh=3) # esse parametro só exclui colunas com um minimo de 3 valores não missing (agora a coluna foi excluida)

     aluno  idade
0     Joao     30
1    Maria     25
2   Helena     18
3     Joel     29
4  Gabriel     45

Por fim, você poderia chegar a conclusão que o melhor seria imputar dados nos valores missing em vez de excluí-los. Veja como fazer isso:

In [ ]:
df

     aluno  idade  altura
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7

In [ ]:
df.fillna(2) # preenche 2 em todos os valores missing

     aluno  idade  altura
0     Joao     30     2.0
1    Maria     25     2.0
2   Helena     18     2.0
3     Joel     29     1.6
4  Gabriel     45     1.7

In [ ]:
df.fillna(df['altura'].mean()) # preenche com a média de Altura em todos os valores missing da variável

     aluno  idade  altura
0     Joao     30    1.65
1    Maria     25    1.65
2   Helena     18    1.65
3     Joel     29    1.60
4  Gabriel     45    1.70

## Dados duplicados

Outra operação comum em manipulação de dados é lidar com dados duplicados. Veja a seguir um caso desse tipo.

In [ ]:
df

     aluno  idade  altura
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7

In [ ]:
df2 = pd.concat((df,df))
df2

     aluno  idade  altura
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7

In [ ]:
df3 = df2.sort_values(by='aluno',ascending=True) # Ordena o dataframe por ordem alfabética crescente pela variável "aluno"
df3

     aluno  idade  altura
4  Gabriel     45     1.7
4  Gabriel     45     1.7
2   Helena     18     NaN
2   Helena     18     NaN
0     Joao     30     NaN
0     Joao     30     NaN
3     Joel     29     1.6
3     Joel     29     1.6
1    Maria     25     NaN
1    Maria     25     NaN

In [ ]:
df3.duplicated() # Com o método duplicated() podemos saber quais linhas tem valores duplicados

4    False
4     True
2    False
2     True
0    False
0     True
3    False
3     True
1    False
1     True
dtype: bool

In [ ]:
df3.duplicated().sum() # Contando quantas linhas tem valores duplicados

5

In [ ]:
df3.drop_duplicates()

     aluno  idade  altura
4  Gabriel     45     1.7
2   Helena     18     NaN
0     Joao     30     NaN
3     Joel     29     1.6
1    Maria     25     NaN

<b>Dica:</b> Verifique a documentação do método .drop_duplicates() para mais operações, como por exemplo remover somente a ultima linha duplicada.

## Criação de Variáveis e Alteração de Variáveis

Vamos falar agora sobre como criar novas variáveis em um DataFrame existente ou mesmo como alterar as variáveis.

In [ ]:
df

     aluno  idade  altura
0     Joao     30     NaN
1    Maria     25     NaN
2   Helena     18     NaN
3     Joel     29     1.6
4  Gabriel     45     1.7

In [ ]:
# Vamos criar uma variável chamada "Faculdade"
df['Faculdade'] = 'USP'

In [ ]:
df

     aluno  idade  altura Faculdade
0     Joao     30     NaN       USP
1    Maria     25     NaN       USP
2   Helena     18     NaN       USP
3     Joel     29     1.6       USP
4  Gabriel     45     1.7       USP

In [ ]:
# Vamos criar uma variável condicional de acordo com a idade do aluno.

In [ ]:
df['Tipo_Curso'] = np.where(df['idade'] < 30 , 'Graduacao', 'Pos_Graduacao') # usamos o método Where do Numpy para isso

In [ ]:
df

     aluno  idade  altura Faculdade     Tipo_Curso
0     Joao     30     NaN       USP  Pos_Graduacao
1    Maria     25     NaN       USP      Graduacao
2   Helena     18     NaN       USP      Graduacao
3     Joel     29     1.6       USP      Graduacao
4  Gabriel     45     1.7       USP  Pos_Graduacao

In [ ]:
# Vamos criar uma variável condicional do valor do curso (que vamos supor que dependa da idade 
# da seguinte forma: Valor = 200*Idade)
df['Valor'] = 200*df['idade']
df

     aluno  idade  altura Faculdade     Tipo_Curso  Valor
0     Joao     30     NaN       USP  Pos_Graduacao   6000
1    Maria     25     NaN       USP      Graduacao   5000
2   Helena     18     NaN       USP      Graduacao   3600
3     Joel     29     1.6       USP      Graduacao   5800
4  Gabriel     45     1.7       USP  Pos_Graduacao   9000

## Manipulação de Datas

Por fim, vamos entender como trabalhar com datas no Pandas. Esse tipo de manipulação é vital para trabalhar com DataFrames em situações reais do mercado, pois sempre estaremos interessados em desenvolver modelos que possam endereçar problemas que aconteceram (ou acontecerão) em determinado momento no tempo. Veja:

In [ ]:
# Começamos com uma data qualquer
data = pd.to_datetime('2019-11-01')
data

Timestamp('2019-11-01 00:00:00')

In [ ]:
data.strftime('%d') # Retorna o dia de data

'01'

In [ ]:
data.strftime('%m') # Retorna o mês de data

'11'

In [ ]:
data.strftime('%Y') # Retorna o ano de data

'2019'

In [ ]:
# podemos incrementar a data em alguns dias, por exemplo, 4 dias.
data + pd.to_timedelta(np.arange(5),'D')

DatetimeIndex(['2019-11-01', '2019-11-02', '2019-11-03', '2019-11-04',
               '2019-11-05'],
              dtype='datetime64[ns]', freq=None)

In [ ]:
# Criando um dataframe com as datas
df_t = pd.DataFrame( ( data + pd.to_timedelta(np.arange(5),'D') ),columns=['Data_Matricula'])

In [ ]:
df_t

  Data_Matricula
0     2019-11-01
1     2019-11-02
2     2019-11-03
3     2019-11-04
4     2019-11-05

In [ ]:
# Vamos unir esse novo dataframe para nossa tabela de alunos
df2 = pd.concat((df,df_t),axis = 1)
df2

     aluno  idade  altura Faculdade     Tipo_Curso  Valor Data_Matricula
0     Joao     30     NaN       USP  Pos_Graduacao   6000     2019-11-01
1    Maria     25     NaN       USP      Graduacao   5000     2019-11-02
2   Helena     18     NaN       USP      Graduacao   3600     2019-11-03
3     Joel     29     1.6       USP      Graduacao   5800     2019-11-04
4  Gabriel     45     1.7       USP  Pos_Graduacao   9000     2019-11-05

In [ ]:
df2.dtypes

aluno                     object
idade                      int64
altura                   float64
Faculdade                 object
Tipo_Curso                object
Valor                      int64
Data_Matricula    datetime64[ns]
dtype: object

O Pandas tem vários outros métodos para lidar com datas. Seguem alguns exemplos:

In [ ]:
# Cria datas entre um intervalo
pd.date_range('2019-10-05','2019-10-15',freq='B')

DatetimeIndex(['2019-10-07', '2019-10-08', '2019-10-09', '2019-10-10',
               '2019-10-11', '2019-10-14', '2019-10-15'],
              dtype='datetime64[ns]', freq='B')

Chegamos ao fim de mais uma seção. O Pandas tem uma série de outras funções que não foram cobertas aqui. Eventualmente, ao longo do curso vamos nos deparar com novas funções deste pacote. Quando for necessário, acesse a documentação original em https://pandas.pydata.org/docs/reference/index.html ou busque sua dúvida no StackOverflow (uma das maiores fontes de conhecimento em programação da internet).

Na próxima aula, vamos falar sobre o <b>Matplotlib</b> e  <b>seaborn</b> as demais formas de visualização de dados no Python! Até lá !!!