# 🛒 Trilha de Aprendizado no Varejo

Este é o gabarito oficial com as respostas em código para as 30 etapas (Learnings) focadas em `pandas` e `numpy` utilizando o dataset de supermercado. 
Utilize este notebook como espelho para validar as explicações e códigos durante a aula.

### Learning 1: Setup de Ambiente Cloud
**Tarefa:** Importe `pandas` como `pd` e `numpy` como `np`.

In [99]:
import pandas as pd
import numpy as np

### Learning 2: Ingestão de Dados Transacionais
**Tarefa:** Carregue o arquivo 'supermarket.csv' em um DataFrame chamado `df`.

In [100]:
# Lendo o arquivo CSV
df = pd.read_csv('./dataset/supermarket.csv')

### Learning 3: Amostragem de Qualidade (QA)
**Tarefa:** Use um comando para exibir as 5 primeiras linhas do DataFrame.

In [101]:
# Visualizando os primeiros registros
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

### Learning 4: Mapeamento de Esquema (Schema)
**Tarefa:** Exiba o resumo de informações estruturais do DataFrame (método `info`).

In [102]:
# Exibe estrutura, tipos de colunas e uso de memória
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

### Learning 5: Baseline Estatístico Financeiro
**Tarefa:** Gere as estatísticas descritivas básicas do DataFrame.

In [103]:
# Gera estatísticas como média, min, max, e quartis das colunas numéricas
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

### Learning 6: Auditoria de Integridade (Missing Values)
**Tarefa:** Calcule a soma de valores nulos para cada coluna do dataset.

In [104]:
# Identifica e soma a quantidade de nulos por coluna
df.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

### Learning 7: Expurgo de Dados Corrompidos
**Tarefa:** Remova todas as linhas que contenham algum valor nulo para garantir a integridade dos cálculos (atualize o DataFrame `df`).

In [105]:
# Remove linhas com qualquer nulo e sobrescreve o dataframe original
df = df.dropna()

### Learning 8: Padronização de Sistemas Legados

**Tarefa 1:** Como o nosso dataset possui a coluna Region (Região), podemos usar uma regra de negócio para definir que cada região operacional representa uma filial diferente.Com base na distribuição dos nossos dados, vamos mapear as filiais assim:Região West (Oeste) $\rightarrow$ Filial ARegião East (Leste) $\rightarrow$ Filial BRegião Central (Central) $\rightarrow$ Filial CRegião South (Sul) $\rightarrow$ Filial D

**Tarefa 2:** Renomeie as colunas 'Branch' para 'Filial' e 'City' para 'Cidade'.

In [106]:

# 2. Cria um dicionário com a regra de mapeamento
regras_filiais = {
    'West': 'A',
    'East': 'B',
    'Central': 'C',
    'South': 'D'
}

# 3. Cria a nova coluna 'Branch' usando a função .map()
df['Branch'] = df['Region'].map(regras_filiais)

# 4. Verifica o resultado contando quantas linhas cada filial possui
print(df['Branch'].value_counts())
# Renomeia colunas usando um dicionário
df = df.rename(columns={'Branch': 'Filial', 'City': 'Cidade'})
df.head(2)

Branch
A    3140
B    2774
C    2277
D    1598
Name: count, dtype: int64

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,Cidade,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Filial
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,D
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,D

### Learning 9: Mapeamento de Linhas de Produto
**Tarefa:** Liste os valores únicos presentes na coluna 'Category'.

In [107]:
# Retorna um array com as categorias únicas
df['Category'].unique()

<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

### Learning 10: Ranqueamento de Meios de Segmento
**Tarefa:** Conte a frequência de cada Segmento aparece.

In [108]:
# Conta quantas vezes cada Segment aparece
df['Segment'].value_counts()

Segment
Consumer       5096
Corporate      2948
Home Office    1745
Name: count, dtype: int64

###  Learning 11: Isolamento de Região (Filtro Simples)
**Tarefa:** Filtre o dataset supermarket.csv para exibir apenas os registros onde a região de vendas (Region) seja igual a 'South' (Sul).

In [109]:
# Aplica o filtro simples na coluna 'Region'
df_sul = df[df['Region'] == 'South']
df_sul.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,Cidade,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Filial
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,D
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,D
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,D
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,D
12,13,CA-2018-114412,15/04/2018,20/04/2018,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,D

### Learning 12:Rastreamento Específico (Filtro AND)
**Tarefa:** Filtre o dataset supermarket.csv para exibir apenas os pedidos que foram enviados por entrega rápida (Ship Mode igual a 'First Class') E que pertençam à categoria de tecnologia (Category igual a 'Technology').

In [110]:
# Aplica o filtro com duas condições usando o operador '&' (AND)
# IMPORTANTE: No Pandas, cada condição deve estar entre parênteses
df_filtrado = df[(df['Ship Mode'] == 'First Class') & (df['Category'] == 'Technology')]
# Exibe a quantidade de registros que atendem aos dois critérios
print(f"Total de pedidos de Tecnologia com entrega First Class: {len(df_filtrado)}")

Total de pedidos de Tecnologia com entrega First Class: 297

### Learning 13:  Foco em Mobiliário (Filtro OR)
Tarefa: Filtre o dataset supermarket.csv para exibir apenas as vendas que pertençam às subcategorias de cadeiras ('Chairs') OU mesas ('Tables').

In [111]:
# Método 1: Usando o operador lógico '|' (OR)
df_moveis = df[(df['Sub-Category'] == 'Chairs') | (df['Sub-Category'] == 'Tables')]

# Método 2 (Melhor prática): Usando .isin() para múltiplos valores na mesma coluna
df_moveis_isin = df[df['Sub-Category'].isin(['Chairs', 'Tables'])]

# Exibe o resultado (ambos os métodos geram o mesmo DataFrame)
print(f"Total de vendas de Cadeiras e Mesas: {len(df_moveis)}")

Total de vendas de Cadeiras e Mesas: 920

### Learning 14: Segmentação de Fidelidade (isin)
**Tarefa:** Utilize o método `isin()` para filtrar registros onde 'Country' seja 'United States'.

In [112]:
# Filtro útil para verificar se o valor está dentro de uma lista
df_members = df[df['Country'].isin(['United States'])]
df_members.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,Cidade,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Filial
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,D
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,D
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,A
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,D
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,D

### Learning 15: Normalização de Registros de Texto
**Tarefa:** Converta todos os nomes na coluna 'Cidade' para letras maiúsculas (UPPERCASE).

In [113]:
# Aplica a transformação de string (str) em toda a coluna
df['Cidade'] = df['Cidade'].str.upper()
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,Cidade,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Filial
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,HENDERSON,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,D
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,HENDERSON,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,D
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,LOS ANGELES,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,A
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,FORT LAUDERDALE,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,D
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,FORT LAUDERDALE,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,D

### Learning 16: Tratamento de Séries Temporais (Datetime)
**Tarefa:** Transforme a coluna 'Date' para o formato `datetime` do Pandas.

In [114]:
# Aplicando no seu DataFrame com o formato correto (Dia/Mês/Ano)
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')# Converte string para formato nativo de data
df['Order Date'].head()

0   2017-11-08
1   2017-11-08
2   2017-06-12
3   2016-10-11
4   2016-10-11
Name: Order Date, dtype: datetime64[us]

### Learning 17: Engenharia de Atributos Temporais
**Tarefa:** Crie uma nova coluna chamada 'Month' extraindo apenas o mês da coluna 'Date'.

In [115]:
# Acessa a propriedade dt (datetime) para extrair o mês
df['Month'] = df['Order Date'].dt.month
df[['Order Date', 'Month']].head()

  Order Date  Month
0 2017-11-08     11
1 2017-11-08     11
2 2017-06-12      6
3 2016-10-11     10
4 2016-10-11     10

### Learning 18: Fila de Atendimento VIP (Ordenação)
**Tarefa:** Ordene o dataset pelo valor da coluna 'Sales' de forma decrescente e exiba os 10 primeiros.

In [116]:
# Ordena do maior para o menor e pega os 10 primeiros
df.sort_values(by='Sales', ascending=False).head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,Cidade,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Filial,Month
2697,2698,CA-2015-145317,2015-03-18,23/03/2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,JACKSONVILLE,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,D,3
6826,6827,CA-2017-118689,2017-10-02,09/10/2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,LAFAYETTE,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,C,10
8153,8154,CA-2018-140151,2018-03-23,25/03/2018,First Class,RB-19360,Raymond Buch,Consumer,United States,SEATTLE,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,A,3
2623,2624,CA-2018-127180,2018-10-22,24/10/2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,NEW YORK CITY,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,B,10
4190,4191,CA-2018-166709,2018-11-17,22/11/2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,NEWARK,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,B,11
9039,9040,CA-2017-117121,2017-12-17,21/12/2017,Standard Class,AB-10105,Adrian Barton,Consumer,United States,DETROIT,Michigan,48205.0,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,C,12
4098,4099,CA-2015-116904,2015-09-23,28/09/2015,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,MINNEAPOLIS,Minnesota,55407.0,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,C,9
4277,4278,US-2017-107440,2017-04-16,20/04/2017,Standard Class,BS-11365,Bill Shonely,Corporate,United States,LAKEWOOD,New Jersey,8701.0,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,B,4
8488,8489,CA-2017-158841,2017-02-02,04/02/2017,Second Class,SE-20110,Sanjit Engle,Consumer,United States,ARLINGTON,Virginia,22204.0,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,D,2
6425,6426,CA-2017-143714,2017-05-23,27/05/2017,Standard Class,CC-12370,Christopher Conant,Consumer,United States,PHILADELPHIA,Pennsylvania,19120.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976,B,5

### Learning 19: Reconstrução de Métricas (Matemática Vetorizada)
**Tarefa:** Crie uma nova coluna simulando um imposto adicional estático: adicione 2% sobre o valor da coluna 'Sales'.

In [117]:
# Multiplicação vetorizada em toda a coluna
df['Total_com_imposto'] = df['Sales'] * 1.02
df[['Sales', 'Total_com_imposto']].head()

      Sales  Total_com_imposto
0  261.9600          267.19920
1  731.9400          746.57880
2   14.6200           14.91240
3  957.5775          976.72905
4   22.3680           22.81536

### Learning 20: Bônus de Produtividade (Condicional np.where)
**Tarefa:** Use `np.where` para criar uma coluna 'Ticket_Type', marcando como 'High' se o 'Sales' for maior que 500, e 'Low' caso contrário.

In [118]:
# Atribuição condicional rápida com NumPy
df['Ticket_Type'] = np.where(df['Sales'] > 500, 'High', 'Low')
df[['Sales', 'Ticket_Type']].head(10)

      Sales Ticket_Type
0  261.9600         Low
1  731.9400        High
2   14.6200         Low
3  957.5775        High
4   22.3680         Low
5   48.8600         Low
6    7.2800         Low
7  907.1520        High
8   18.5040         Low
9  114.9000         Low

### Learning 21: Faturamento Trimestral (Groupby)
**Tarefa:** Agrupe os dados por 'Filial' e calcule a soma da coluna 'Total'.

In [119]:
# Soma agrupada simples
df.groupby('Filial')['Sales'].sum()

Filial
A    710219.6845
B    660589.3560
C    492646.9132
D    389151.4590
Name: Sales, dtype: float64

### Learning 22: Micro-Segmentação de Mercado
**Tarefa:** Agrupe pelos campos 'Segment' e 'Ship Mode' e calcule a soma de vendas ('Sales').

In [123]:
# Agrupamento por múltiplas colunas passadas como lista
df.groupby(['Segment', 'Ship Mode'])['Sales'].sum()

Segment      Ship Mode
Consumer     First Class       158104.9470
             Same Day           57452.2730
             Second Class      229410.3356
             Standard Class    701740.5954
Corporate    First Class       102580.0539
             Same Day           45121.3230
             Second Class      139045.2908
             Standard Class    395465.1671
Home Office  First Class        84887.2564
             Same Day           22645.4430
             Second Class       80743.3530
             Standard Class    235411.3745
Name: Sales, dtype: float64

### Learning 23: Estratégia de Precificação Dinâmica
**Tarefa:** Agrupe por 'Product line' e calcule o preço unitário ('Unit price') mínimo, máximo e médio usando `.agg()`.

In [ ]:
# Aplica diferentes funções de agregação ao mesmo tempo
df.groupby('Ship Mode')['Sales'].agg(['min', 'max', 'mean'])

                  min       max        mean
Ship Mode
First Class     0.984  13999.96  230.228020
Same Day        0.556   7999.98  232.749143
Second Class    1.188   8749.95  236.296149
Standard Class  0.444  22638.48  227.836748

### Learning 24: Matriz Executiva de Avaliações (Pivot Table)
**Tarefa:** Construa uma Pivot Table calculando a média de 'Sales' por 'Cidade' e 'Filial'.

In [129]:
# 2. Recria a coluna 'Branch' (Filial) baseada nas Regiões (conforme Learning 15)
df['Filial'] = df['Region'].map({'West': 'A', 'East': 'B', 'Central': 'C', 'South': 'D'})

# 3. Cria a Tabela Dinâmica usando Sales (Vendas), City (Cidade) e Branch (Filial)
tabela_dinamica = pd.pivot_table(df, values='Sales', index='Cidade', columns='Filial', aggfunc='mean')

# 4. Formata o resultado para ficar legível (arredonda para 2 casas e substitui 'NaN' por '-')
print(tabela_dinamica.head(10).round(2).fillna('-'))

Filial            A       B       C       D
Cidade
ABERDEEN          -       -    25.5       -
ABILENE           -       -    1.39       -
AKRON             -  136.21       -       -
ALBUQUERQUE  158.58       -       -       -
ALEXANDRIA        -       -       -  344.97
ALLEN             -       -   72.55       -
ALLENTOWN         -  121.89       -       -
ALTOONA           -   10.23       -       -
AMARILLO          -       -  377.31       -
ANAHEIM      294.77       -       -       -

### Learning 25: Frequência Cruzada e Agregação (Crosstab)
Tarefa: Use pd.crosstab para descobrir qual categoria de produto gerou o maior volume de vendas em cada Filial.

In [132]:
df['Branch'] = df['Region'].map({'West': 'A', 'East': 'B', 'Central': 'C', 'South': 'D'})

# 2. Cria o Crosstab cruzando Filial x Categoria, somando as Vendas
tabela_cruzada = pd.crosstab(
    index=df['Branch'], 
    columns=df['Category'], 
    values=df['Sales'], 
    aggfunc='sum'
)

# 3. Formata e exibe os resultados para encontrarmos os "melhores"
print("Total de Vendas por Filial e Categoria:\n")
print(tabela_cruzada.round(2))

Total de Vendas por Filial e Categoria:

Category  Furniture  Office Supplies  Technology
Branch
A         245348.25        217466.51   247404.93
B         201341.29        197731.30   261516.77
C         160317.46        163590.24   168739.21
D         116531.48        124424.77   148195.21

### Learning 26: Detecção de Anomalias (Percentil numpy)
**Tarefa:** Utilize o NumPy para descobrir qual é o valor 'Sales' exato que representa o percentil 99.

In [134]:
# Encontra o limite estatístico do percentil 99
p99 = np.percentile(df['Sales'], 99)
print(f'O percentil 99 é: {p99:.2f}')

O percentil 99 é: 2456.61

### Learning 27: Compliance e LGPD (Drop Columns)
**Tarefa:** Remova permanentemente a coluna 'Filial' do DataFrame.

In [136]:
# Remove a coluna do dataframe
df = df.drop(columns=['Filial'])
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'Cidade', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Month', 'Total_com_imposto', 'Ticket_Type',
       'Branch'],
      dtype='str')

### Learning 28: Regras Tributárias Complexas (Apply com Lambda)
**Tarefa:** Use uma função `lambda` com `.apply()` para recalcular a coluna 'Total' adicionando 5% APENAS se a categoria for 'Electronic accessories'.

In [137]:
# Aplica lógica condicional linha a linha sobre o dataset
df['Total'] = df.apply(lambda row: row['Sales'] * 1.05 if row['Category'] == 'Electronic accessories' else row['Sales'], axis=1)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,Cidade,...,Product ID,Category,Sub-Category,Product Name,Sales,Month,Total_com_imposto,Ticket_Type,Branch,Total
0,1,CA-2017-152156,2017-11-08,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,HENDERSON,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,11,267.19920,Low,D,261.9600
1,2,CA-2017-152156,2017-11-08,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,HENDERSON,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,11,746.57880,High,D,731.9400
2,3,CA-2017-138688,2017-06-12,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,LOS ANGELES,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,6,14.91240,Low,A,14.6200
3,4,US-2016-108966,2016-10-11,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,FORT LAUDERDALE,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,10,976.72905,High,D,957.5775
4,5,US-2016-108966,2016-10-11,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,FORT LAUDERDALE,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,10,22.81536,Low,D,22.3680

### Learning 29: Apresentação Financeira (Arredondamento numpy)
**Tarefa:** Utilize o NumPy (`np.round`) para arredondar a coluna 'Sales' para exatamente 2 casas decimais.

In [138]:
# Arredondamento padronizado para formato moeda
df['Total'] = np.round(df['Sales'], 2)
df['Total'].head()

0    261.96
1    731.94
2     14.62
3    957.58
4     22.37
Name: Total, dtype: float64

### Learning 30: Pipeline de Ingestão Cloud (Exportação)
**Tarefa:** Exporte o DataFrame tratado para um arquivo 'supermarket_analytics.csv', garantindo que o índice (index) do Pandas NÃO seja gravado.

In [139]:
# Salva o arquivo CSV descartando os números do índice originais
df.to_csv('supermarket_analytics.csv', index=False)
print('Exportado com sucesso!')

Exportado com sucesso!