# Preparação dos Dados (Data Prep)

## Estudo de Caso: Qualidade na Central de Atendimento

Uma empresa de Contact Center fez uma pesquisa no momento da contratação de um grupo de colaboradores (agentes de atendimento) através do <a href="https://pt.surveymonkey.com/">Survey Monkey</a>. Após 6 meses da contratação verificou se quais colaboradores atingiram um bom desempenho de Qualidade e dos indicadores operacionais e estes agentes foram identificados com o valor 1 na coluna "Target".

Antes de criar um modelo que possa ser utilizado para entender os fatores mais associados a uma boa performance futura, o time de Atendimento ao Cliente precisa processar os dados brutos da ferramenta de pesquisa e realizar algumas análises exploratórias. Você como Cientista de Dados está encarregado desta tarefa de preparação dos dados brutos.

### Dados Brutos do Questionário

In [1]:
import pandas as pd

In [2]:
df_bruto = pd.read_csv('dados_contact_center_survey.csv', 
                       sep = ";", 
                       low_memory=False, 
                       header=[0,1])
df_bruto.head()

,Unnamed: 0_level_0,Unnamed: 1_level_0,Você está trabalhando no Campus ou em Casa?,Unnamed: 3_level_0,Qual o tempo gasto no trajeto da sua residência até a empresa?,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Qual a sua escolaridade?,...,Pessoas fortes vêm de ambientes competitivos.,Unnamed: 309_level_0,Unnamed: 310_level_0,Unnamed: 311_level_0,Unnamed: 312_level_0,Gosto de ter um trabalho exigente.,Unnamed: 314_level_0,Unnamed: 315_level_0,Unnamed: 316_level_0,Unnamed: 317_level_0
,Id_Agente,Cliente,1 - Campus,1 - Casa,2 - Até 30min,2 - De 30min à 1h,2 - De 1h à 1h30,2 - De 1h30 à 2h,2 - Acima de 2h,3 - Ensino Médio completo,...,64 - 5 - Concordo totalmente,64 - 4 - Concordo,64 - 3 - Indiferente,64 - 2 - Discordo,64 - 1 - Discordo totalmente,65 - 5 - Concordo totalmente,65 - 4 - Concordo,65 - 3 - Indiferente,65 - 2 - Discordo,65 - 1 - Discordo totalmente
0,1,Cliente 1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Cliente 2,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,Cliente 2,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,4,Cliente 3,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,5,Cliente 4,0,1,0,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0

In [3]:
df_bruto.shape

(7240, 318)

### Dados de Desempenho

In [4]:
df_desempenho = pd.read_csv('dados_contact_center_survey_desempenho.csv', 
                            sep = ";", 
                            low_memory=False)
df_desempenho.head()

   Id_Agente  Target
0          1       1
1          2       1
2          3       1
3          4       0
4          5       0

### Dados Esperados pelo time de Atendimento ao Cliente para a Análise Exploratória

In [5]:
df_proc = pd.read_csv('dados_contact_center_survey_processado.csv', 
                      sep = ";")

In [6]:
df_proc.head()

,Id_Agente,P 01: Você está trabalhando no Campus ou em Casa?,P 02: Qual o tempo gasto no trajeto da sua residência até a empresa?,P 03: Qual a sua escolaridade?,P 04: Qual a sua área de estudo?,P 05: Você possui dependentes?,P 06: Quantos dependentes você possui?,P 07: Qual seu conhecimento em inglês?,P 08: Qual seu conhecimento em espanhol?,"P 09: Antes de trabalhar na empresa, você tinha experiência em Contact Center?",...,P 58: Os melhores resultados vêm do trabalho em equipe.,P 59: Baseio meu trabalho em relações interpessoais.,P 60: Fico tenso quando estou trabalhando.,P 61: Providencio soluções para os meus problemas com rapidez.,P 62: Demonstro meu valor nas horas difíceis.,P 63: Falta de tempo não me assusta.,P 64: Pessoas fortes vêm de ambientes competitivos.,P 65: Gosto de ter um trabalho exigente.,Cliente,Target
0,1,1 - Casa,0 - Sem resposta,3 - Ensino Superior incompleto,4 - Humanas,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Intermediário,9 - Não,...,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,Cliente 1,1
1,2,1 - Casa,0 - Sem resposta,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Não tenho conhecimento em inglês,8 - Não tenho conhecimento em espanhol,9 - Sim,...,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,Cliente 2,1
2,3,1 - Casa,0 - Sem resposta,3 - Ensino Superior cursando,4 - Gestão de Pessoas/Negócios,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Não tenho conhecimento em espanhol,9 - Sim,...,58 - 4 - Concordo,59 - 2 - Discordo,60 - 3 - Indiferente,61 - 3 - Indiferente,62 - 4 - Concordo,63 - 3 - Indiferente,64 - 4 - Concordo,65 - 2 - Discordo,Cliente 2,1
3,4,1 - Casa,0 - Sem resposta,3 - Ensino Superior concluído,4 - Saúde,5 - Não,0 - Sem resposta,7 - Básico,8 - Não tenho conhecimento em espanhol,9 - Não,...,58 - 4 - Concordo,59 - 4 - Concordo,60 - 4 - Concordo,61 - 4 - Concordo,62 - 4 - Concordo,63 - 3 - Indiferente,64 - 2 - Discordo,65 - 3 - Indiferente,Cliente 3,0
4,5,1 - Casa,0 - Sem resposta,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Avançado,8 - Básico,9 - Não,...,58 - 4 - Concordo,59 - 4 - Concordo,60 - 3 - Indiferente,61 - 4 - Concordo,62 - 4 - Concordo,63 - 4 - Concordo,64 - 3 - Indiferente,65 - 3 - Indiferente,Cliente 4,0

## Correção dos nomes das variáveis
Perceba que o dataframe orginal tem um problema no cabeçalho: temos duas linhas para definir o nome das variáveis com cada resposta dos colaboradores. Para corrigir isso, realizaremos algumas etapas utilizando diferentes funções do Pandas e vários recursos do Python. Por isso, é importante que o Cientista de Dados conheça diversas ferramentas diferentes para poder escolher a mais adequada para se utilizar em cada tarefa.

In [7]:
df_bruto.head()

,Unnamed: 0_level_0,Unnamed: 1_level_0,Você está trabalhando no Campus ou em Casa?,Unnamed: 3_level_0,Qual o tempo gasto no trajeto da sua residência até a empresa?,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Qual a sua escolaridade?,...,Pessoas fortes vêm de ambientes competitivos.,Unnamed: 309_level_0,Unnamed: 310_level_0,Unnamed: 311_level_0,Unnamed: 312_level_0,Gosto de ter um trabalho exigente.,Unnamed: 314_level_0,Unnamed: 315_level_0,Unnamed: 316_level_0,Unnamed: 317_level_0
,Id_Agente,Cliente,1 - Campus,1 - Casa,2 - Até 30min,2 - De 30min à 1h,2 - De 1h à 1h30,2 - De 1h30 à 2h,2 - Acima de 2h,3 - Ensino Médio completo,...,64 - 5 - Concordo totalmente,64 - 4 - Concordo,64 - 3 - Indiferente,64 - 2 - Discordo,64 - 1 - Discordo totalmente,65 - 5 - Concordo totalmente,65 - 4 - Concordo,65 - 3 - Indiferente,65 - 2 - Discordo,65 - 1 - Discordo totalmente
0,1,Cliente 1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Cliente 2,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,Cliente 2,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,4,Cliente 3,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,5,Cliente 4,0,1,0,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0

### Identificação do índice dos textos das questões.
Esse índice será utilizado nas etapas seguintes.

In [8]:
indices = [i for i, c in enumerate(df_bruto.columns) if not c[0].startswith('Unnamed')]
indices

[2,
 4,
 9,
 15,
 27,
 29,
 32,
 37,
 42,
 45,
 49,
 59,
 71,
 73,
 75,
 79,
 84,
 86,
 88,
 90,
 93,
 98,
 103,
 108,
 113,
 118,
 123,
 128,
 133,
 138,
 143,
 148,
 153,
 158,
 163,
 168,
 173,
 178,
 183,
 188,
 193,
 198,
 203,
 208,
 213,
 218,
 223,
 228,
 233,
 238,
 243,
 248,
 253,
 258,
 263,
 268,
 273,
 278,
 283,
 288,
 293,
 298,
 303,
 308,
 313]

### Obtenção do texto da questão.
Esse texto será utilizado para atribuir os nomes às variáveis.

In [9]:
questions = [c[0] for c in df_bruto.columns if not c[0].startswith('Unnamed')]
questions

['Você está trabalhando no Campus ou em Casa?',
 'Qual o tempo gasto no trajeto da sua residência até a empresa?',
 'Qual a sua escolaridade?',
 'Qual a sua área de estudo?',
 'Você possui dependentes?',
 'Quantos dependentes você possui?',
 'Qual seu conhecimento em inglês?',
 'Qual seu conhecimento em espanhol?',
 'Antes de trabalhar na empresa, você tinha experiência em Contact Center?',
 'Por quanto tempo você trabalhou em Contact Center?',
 'Qual área de atendimento você atua ou atuou por mais tempo?',
 'Em qual área você trabalhou?',
 'Você tem experiência anterior com vendas em outro segmento?',
 'Você possui disponibilidade pra trabalhar em casa?',
 'Você possui Desktop ou Notebook?',
 'Qual sistema operacional utiliza?',
 'Seu dispositivo possui Webcam?',
 'Você possui Headset USB?',
 'Você possui internet FIXA em casa?',
 'Qual a velocidade da sua internet?',
 'Pedir ajuda não é sinal de fraqueza.',
 'Não gosto de situações que requerem que eu me comporte de forma controlada.',
 'Gosto de dizer o que penso.',
 'Gosto de fazer as coisas do meu jeito e não ligo para o que possam pensar.',
 'Não gosto que deveres e responsabilidades que me façam sentir sob pressão.',
 'Não tenho medo de criticar pessoas em cargos de liderança.',
 'Gosto de me sentir livre para fazer o que bem entender.',
 'Gosto de trabalhar sozinho e independentemente.',
 'Gosto de realizar tarefas melhor do que os outros.',
 'Gostaria de ser líder em qualquer emprego, profissão, área ou especialidade.',
 'Gosto de realizar tarefas que, na opinião dos outros , requerem competência e esforço.',
 'Gosto de ser bem sucedido no que faço.',
 'Gosto de resolver problemas que são difíceis para os outros.',
 'Ouvir um “parabéns” é a melhor recompensa.',
 'A cada dia vejo o desafio de alcançar algo a mais.',
 'O objetivo de cada esforço é a satisfação total do cliente.',
 'Sempre tento atingir uma meta audaciosa.',
 'Gosto de ter tudo planejado com antecedência caso for viajar.',
 'Gosto de ter minhas coisas organizadas em minha mesa ou local de trabalho.',
 'Gosto de planejar antes de realizar algo difícil.',
 'Não quero que alterem meu horário com frequência.',
 'Muito pode ser alcançado com organização e ordem.',
 'Tenho ciência de quando realizei bem meu trabalho.',
 'Gosto de escrever as tarefas que tenho a fazer.',
 'Sinto-me seguro quando há procedimentos a serem seguidos.',
 'Sempre olho a data de validade do produto antes de comprá-lo.',
 'Uso algum tipo de agenda diariamente.',
 'Gosto de seguir instruções e fazer o que se espera de mim.',
 'Gosto de compartilhar.',
 'Gosto de ajudar as pessoas.',
 'Trato o próximo com gentileza e compaixão.',
 'Gosto de pessoas que me contam confidências e problemas.',
 'Perdoo as pessoas que às vezes me machucam.',
 'Entendo quando alguém precisa de ajuda.',
 'Se você ouvir alguém com atenção, você entenderá o porquê do humor dele.',
 'A maioria das pessoas precisam de algum tipo de apoio.',
 'É bom trabalhar com meus colegas de trabalho.',
 'Os melhores resultados vêm do trabalho em equipe.',
 'Baseio meu trabalho em relações interpessoais.',
 'Fico tenso quando estou trabalhando.',
 'Providencio soluções para os meus problemas com rapidez.',
 'Demonstro meu valor nas horas difíceis.',
 'Falta de tempo não me assusta.',
 'Pessoas fortes vêm de ambientes competitivos.',
 'Gosto de ter um trabalho exigente.']

### Definição das fatias do DataFrame.
Essas fatias serão utilizadas para selecionar os blocos de variáveis relacionados a cada questão.

In [10]:
slices = [slice(i, j) for i, j in zip(indices, indices[1:] + [None])]
slices

[slice(2, 4, None),
 slice(4, 9, None),
 slice(9, 15, None),
 slice(15, 27, None),
 slice(27, 29, None),
 slice(29, 32, None),
 slice(32, 37, None),
 slice(37, 42, None),
 slice(42, 45, None),
 slice(45, 49, None),
 slice(49, 59, None),
 slice(59, 71, None),
 slice(71, 73, None),
 slice(73, 75, None),
 slice(75, 79, None),
 slice(79, 84, None),
 slice(84, 86, None),
 slice(86, 88, None),
 slice(88, 90, None),
 slice(90, 93, None),
 slice(93, 98, None),
 slice(98, 103, None),
 slice(103, 108, None),
 slice(108, 113, None),
 slice(113, 118, None),
 slice(118, 123, None),
 slice(123, 128, None),
 slice(128, 133, None),
 slice(133, 138, None),
 slice(138, 143, None),
 slice(143, 148, None),
 slice(148, 153, None),
 slice(153, 158, None),
 slice(158, 163, None),
 slice(163, 168, None),
 slice(168, 173, None),
 slice(173, 178, None),
 slice(178, 183, None),
 slice(183, 188, None),
 slice(188, 193, None),
 slice(193, 198, None),
 slice(198, 203, None),
 slice(203, 208, None),
 slice(208, 213, None),
 slice(213, 218, None),
 slice(218, 223, None),
 slice(223, 228, None),
 slice(228, 233, None),
 slice(233, 238, None),
 slice(238, 243, None),
 slice(243, 248, None),
 slice(248, 253, None),
 slice(253, 258, None),
 slice(258, 263, None),
 slice(263, 268, None),
 slice(268, 273, None),
 slice(273, 278, None),
 slice(278, 283, None),
 slice(283, 288, None),
 slice(288, 293, None),
 slice(293, 298, None),
 slice(298, 303, None),
 slice(303, 308, None),
 slice(308, 313, None),
 slice(313, None, None)]

### Pipeline de Preparação dos Dados
Em cada bloco de variáveis serão realizados os seguintes processamentos:
1. Atribuição do índice para unificação das perguntas
2. Empilhamento das diversas respostas possíveis: **pd.melt()**
3. Seleção dos registros com respostas

Ao final, teremos em cada linha os colaboradores (respondentes) e em cada coluna as perguntas.

In [11]:
# Cria lista para armazenar cada fatia tratada do DataFrame
data = []

for i, q in enumerate(slices):

    # Obtém a variável Id_Agente para utilizar como índice
    d = pd.concat([df_bruto.iloc[:,0], df_bruto.iloc[:,slices[i]]], axis=1)
    
    # Empilha as diversas respostas possíveis em 1 variável
    d = d.melt(id_vars = 'Id_Agente', var_name=questions[i], col_level=1)
    
    # Seleciona apenas os registros que tiveram resposta
    d = d.loc[d['value'] == 1]
    
    # Define Id_Agente como índice
    d.index = d['Id_Agente']
    
    # Elimina as variáveis Id_Agente e value para evita repetições
    d.drop(['Id_Agente', 'value'], axis=1, inplace=True)
    
    # Adiciona a fatia na lista
    data.append(d)

In [12]:
data[35]

          O objetivo de cada esforço é a satisfação total do cliente.
Id_Agente
6                               36 - 5 - Concordo totalmente
8                               36 - 5 - Concordo totalmente
13                              36 - 5 - Concordo totalmente
16                              36 - 5 - Concordo totalmente
18                              36 - 5 - Concordo totalmente
...                                                      ...
4803                            36 - 1 - Discordo totalmente
6108                            36 - 1 - Discordo totalmente
6407                            36 - 1 - Discordo totalmente
6428                            36 - 1 - Discordo totalmente
6642                            36 - 1 - Discordo totalmente

[6556 rows x 1 columns]

### Preparação das variáveis extra questões

In [13]:
df_prim = df_bruto.iloc[:,0:2].copy()
df_prim.columns = df_prim.columns.droplevel(0)
df_prim.index = df_prim['Id_Agente']
df_prim

           Id_Agente     Cliente
Id_Agente
1                  1   Cliente 1
2                  2   Cliente 2
3                  3   Cliente 2
4                  4   Cliente 3
5                  5   Cliente 4
...              ...         ...
7236            7236   Cliente 6
7237            7237   Cliente 6
7238            7238  Cliente 17
7239            7239   Cliente 6
7240            7240  Cliente 17

[7240 rows x 2 columns]

### Unificação dos Dados

In [14]:
data.insert(0, df_prim)

In [15]:
data

[           Id_Agente     Cliente
 Id_Agente
 1                  1   Cliente 1
 2                  2   Cliente 2
 3                  3   Cliente 2
 4                  4   Cliente 3
 5                  5   Cliente 4
 ...              ...         ...
 7236            7236   Cliente 6
 7237            7237   Cliente 6
 7238            7238  Cliente 17
 7239            7239   Cliente 6
 7240            7240  Cliente 17

 [7240 rows x 2 columns],
           Você está trabalhando no Campus ou em Casa?
 Id_Agente
 6                                          1 - Campus
 7                                          1 - Campus
 10                                         1 - Campus
 13                                         1 - Campus
 24                                         1 - Campus
 ...                                               ...
 7225                                         1 - Casa
 7229                                         1 - Casa
 7232                                         1 - Casa
 7234                                         1 - Casa
 7235                                         1 - Casa

 [7240 rows x 1 columns],
           Qual o tempo gasto no trajeto da sua residência até a empresa?
 Id_Agente
 10                                             2 - Até 30min
 13                                             2 - Até 30min
 196                                            2 - Até 30min
 318                                            2 - Até 30min
 354                                            2 - Até 30min
 ...                                                      ...
 7066                                         2 - Acima de 2h
 7077                                         2 - Acima de 2h
 7079                                         2 - Acima de 2h
 7201                                         2 - Acima de 2h
 7226                                         2 - Acima de 2h

 [2207 rows x 1 columns],
               Qual a sua escolaridade?
 Id_Agente
 2            3 - Ensino Médio completo
 5            3 - Ensino Médio completo
 6            3 - Ensino Médio completo
 7            3 - Ensino Médio completo
 9            3 - Ensino Médio completo
 ...                                ...
 7031       3 - Pós-Graduação concluído
 7141       3 - Pós-Graduação concluído
 7182       3 - Pós-Graduação concluído
 7213       3 - Pós-Graduação concluído
 7215       3 - Pós-Graduação concluído

 [7148 rows x 1 columns],
                Qual a sua área de estudo?
 Id_Agente
 8              4 - Administração/Negócios
 11             4 - Administração/Negócios
 18             4 - Administração/Negócios
 19             4 - Administração/Negócios
 20             4 - Administração/Negócios
 ...                                   ...
 7168       4 - Gestão de Pessoas/Negócios
 7171       4 - Gestão de Pessoas/Negócios
 7179       4 - Gestão de Pessoas/Negócios
 7231       4 - Gestão de Pessoas/Negócios
 7240       4 - Gestão de Pessoas/Negócios

 [4248 rows x 1 columns],
           Você possui dependentes?
 Id_Agente
 7                          5 - Sim
 9                          5 - Sim
 11                         5 - Sim
 15                         5 - Sim
 17                         5 - Sim
 ...                            ...
 7234                       5 - Não
 7236                       5 - Não
 7238                       5 - Não
 7239                       5 - Não
 7240                       5 - Não

 [7107 rows x 1 columns],
           Quantos dependentes você possui?
 Id_Agente
 7                                    6 - 1
 9                                    6 - 1
 17                                   6 - 1
 24                                   6 - 1
 25                                   6 - 1
 ...                                    ...
 7107                         6 - 3 ou mais
 7130                         6 - 3 ou mais
 7147                         6 - 3 ou mais
 7214                         6 - 3 ou mais
 7237                         6 - 3 ou mais

 [2279 rows x 1 columns],
                Qual seu conhecimento em inglês?
 Id_Agente
 4                                    7 - Básico
 6                                    7 - Básico
 8                                    7 - Básico
 9                                    7 - Básico
 11                                   7 - Básico
 ...                                         ...
 7231       7 - Não tenho conhecimento em inglês
 7232       7 - Não tenho conhecimento em inglês
 7235       7 - Não tenho conhecimento em inglês
 7237       7 - Não tenho conhecimento em inglês
 7240       7 - Não tenho conhecimento em inglês

 [7069 rows x 1 columns],
                Qual seu conhecimento em espanhol?
 Id_Agente
 5                                      8 - Básico
 8                                      8 - Básico
 9                                      8 - Básico
 11                                     8 - Básico
 12                                     8 - Básico
 ...                                           ...
 7235       8 - Não tenho conhecimento em espanhol
 7236       8 - Não tenho conhecimento em espanhol
 7237       8 - Não tenho conhecimento em espanhol
 7239       8 - Não tenho conhecimento em espanhol
 7240       8 - Não tenho conhecimento em espanhol

 [7069 rows x 1 columns],
           Antes de trabalhar na empresa, você tinha experiência em Contact Center?
 Id_Agente
 2                                                    9 - Sim
 3                                                    9 - Sim
 6                                                    9 - Sim
 7                                                    9 - Sim
 8                                                    9 - Sim
 ...                                                      ...
 7194                  9 - A empresa é o meu primeiro emprego
 7204                  9 - A empresa é o meu primeiro emprego
 7210                  9 - A empresa é o meu primeiro emprego
 7211                  9 - A empresa é o meu primeiro emprego
 7238                  9 - A empresa é o meu primeiro emprego

 [7069 rows x 1 columns],
           Por quanto tempo você trabalhou em Contact Center?
 Id_Agente
 3                                           10 - Até 6 meses
 8                                           10 - Até 6 meses
 34                                          10 - Até 6 meses
 72                                          10 - Até 6 meses
 101                                         10 - Até 6 meses
 ...                                                      ...
 7226                                    10 - Acima de 2 anos
 7230                                    10 - Acima de 2 anos
 7232                                    10 - Acima de 2 anos
 7237                                    10 - Acima de 2 anos
 7239                                    10 - Acima de 2 anos

 [3627 rows x 1 columns],
           Qual área de atendimento você atua ou atuou por mais tempo?
 Id_Agente
 2                                 11 - Atendimento Receptivo
 6                                 11 - Atendimento Receptivo
 10                                11 - Atendimento Receptivo
 11                                11 - Atendimento Receptivo
 27                                11 - Atendimento Receptivo
 ...                                                      ...
 6435                         11 - Suporte Técnico com Vendas
 6535                         11 - Suporte Técnico com Vendas
 6977                         11 - Suporte Técnico com Vendas
 7022                         11 - Suporte Técnico com Vendas
 7159                         11 - Suporte Técnico com Vendas

 [3627 rows x 1 columns],
           Em qual área você trabalhou?
 Id_Agente
 1                  12 - Administrativo
 4                  12 - Administrativo
 5                  12 - Administrativo
 18                 12 - Administrativo
 19                 12 - Administrativo
 ...                                ...
 7143                       12 - Outros
 7152                       12 - Outros
 7179                       12 - Outros
 7183                       12 - Outros
 7195                       12 - Outros

 [2373 rows x 1 columns],
           Você tem experiência anterior com vendas em outro segmento?
 Id_Agente
 2                                                   13 - Sim
 4                                                   13 - Sim
 5                                                   13 - Sim
 8                                                   13 - Sim
 9                                                   13 - Sim
 ...                                                      ...
 7233                                                13 - Não
 7234                                                13 - Não
 7236                                                13 - Não
 7237                                                13 - Não
 7240                                                13 - Não

 [5976 rows x 1 columns],
           Você possui disponibilidade pra trabalhar em casa?
 Id_Agente
 1                                                   14 - Sim
 2                                                   14 - Sim
 3                                                   14 - Sim
 4                                                   14 - Sim
 5                                                   14 - Sim
 ...                                                      ...
 7209                                                14 - Não
 7210                                                14 - Não
 7228                                                14 - Não
 7238                                                14 - Não
 7239                                                14 - Não

 [6992 rows x 1 columns],
           Você possui Desktop ou Notebook?
 Id_Agente
 2                  15 - Sim, apenas eu uso
 3                  15 - Sim, apenas eu uso
 4                  15 - Sim, apenas eu uso
 6                  15 - Sim, apenas eu uso
 8                  15 - Sim, apenas eu uso
 ...                                    ...
 7203                              15 - Não
 7209                              15 - Não
 7220                              15 - Não
 7238                              15 - Não
 7239                              15 - Não

 [6992 rows x 1 columns],
           Qual sistema operacional utiliza?
 Id_Agente
 20                          16 - Windows XP
 68                          16 - Windows XP
 76                          16 - Windows XP
 109                         16 - Windows XP
 131                         16 - Windows XP
 ...                                     ...
 5162                             16 - Linux
 5569                             16 - Linux
 6004                             16 - Linux
 6568                             16 - Linux
 7176                             16 - Linux

 [5960 rows x 1 columns],
           Seu dispositivo possui Webcam?
 Id_Agente
 2                               17 - Sim
 4                               17 - Sim
 6                               17 - Sim
 8                               17 - Sim
 9                               17 - Sim
 ...                                  ...
 7214                            17 - Não
 7217                            17 - Não
 7226                            17 - Não
 7233                            17 - Não
 7234                            17 - Não

 [5960 rows x 1 columns],
           Você possui Headset USB?
 Id_Agente
 1                         18 - Sim
 2                         18 - Sim
 3                         18 - Sim
 6                         18 - Sim
 8                         18 - Sim
 ...                            ...
 7222                      18 - Não
 7223                      18 - Não
 7230                      18 - Não
 7233                      18 - Não
 7240                      18 - Não

 [5960 rows x 1 columns],
           Você possui internet FIXA em casa?
 Id_Agente
 1                                   19 - Sim
 2                                   19 - Sim
 3                                   19 - Sim
 4                                   19 - Sim
 5                                   19 - Sim
 ...                                      ...
 6845                                19 - Não
 6847                                19 - Não
 6962                                19 - Não
 7000                                19 - Não
 7133                                19 - Não

 [6424 rows x 1 columns],
           Qual a velocidade da sua internet?
 Id_Agente
 27                          20 - Até 15 Mbps
 33                          20 - Até 15 Mbps
 34                          20 - Até 15 Mbps
 47                          20 - Até 15 Mbps
 78                          20 - Até 15 Mbps
 ...                                      ...
 7233                   20 - Acima de 50 Mbps
 7234                   20 - Acima de 50 Mbps
 7236                   20 - Acima de 50 Mbps
 7237                   20 - Acima de 50 Mbps
 7240                   20 - Acima de 50 Mbps

 [6312 rows x 1 columns],
           Pedir ajuda não é sinal de fraqueza.
 Id_Agente
 4                 21 - 5 - Concordo totalmente
 6                 21 - 5 - Concordo totalmente
 8                 21 - 5 - Concordo totalmente
 9                 21 - 5 - Concordo totalmente
 11                21 - 5 - Concordo totalmente
 ...                                        ...
 7186              21 - 1 - Discordo totalmente
 7211              21 - 1 - Discordo totalmente
 7217              21 - 1 - Discordo totalmente
 7238              21 - 1 - Discordo totalmente
 7240              21 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Não gosto de situações que requerem que eu me comporte de forma controlada.
 Id_Agente
 188                             22 - 5 - Concordo totalmente
 192                             22 - 5 - Concordo totalmente
 217                             22 - 5 - Concordo totalmente
 271                             22 - 5 - Concordo totalmente
 282                             22 - 5 - Concordo totalmente
 ...                                                      ...
 7201                            22 - 1 - Discordo totalmente
 7204                            22 - 1 - Discordo totalmente
 7215                            22 - 1 - Discordo totalmente
 7223                            22 - 1 - Discordo totalmente
 7234                            22 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
             Gosto de dizer o que penso.
 Id_Agente
 8          23 - 5 - Concordo totalmente
 12         23 - 5 - Concordo totalmente
 21         23 - 5 - Concordo totalmente
 42         23 - 5 - Concordo totalmente
 44         23 - 5 - Concordo totalmente
 ...                                 ...
 6915       23 - 1 - Discordo totalmente
 6974       23 - 1 - Discordo totalmente
 7051       23 - 1 - Discordo totalmente
 7109       23 - 1 - Discordo totalmente
 7137       23 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Gosto de fazer as coisas do meu jeito e não ligo para o que possam pensar.
 Id_Agente
 205                             24 - 5 - Concordo totalmente
 360                             24 - 5 - Concordo totalmente
 377                             24 - 5 - Concordo totalmente
 449                             24 - 5 - Concordo totalmente
 531                             24 - 5 - Concordo totalmente
 ...                                                      ...
 7223                            24 - 1 - Discordo totalmente
 7225                            24 - 1 - Discordo totalmente
 7227                            24 - 1 - Discordo totalmente
 7229                            24 - 1 - Discordo totalmente
 7236                            24 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Não gosto que deveres e responsabilidades que me façam sentir sob pressão.
 Id_Agente
 12                              25 - 5 - Concordo totalmente
 84                              25 - 5 - Concordo totalmente
 179                             25 - 5 - Concordo totalmente
 185                             25 - 5 - Concordo totalmente
 248                             25 - 5 - Concordo totalmente
 ...                                                      ...
 7221                            25 - 1 - Discordo totalmente
 7227                            25 - 1 - Discordo totalmente
 7234                            25 - 1 - Discordo totalmente
 7237                            25 - 1 - Discordo totalmente
 7239                            25 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Não tenho medo de criticar pessoas em cargos de liderança.
 Id_Agente
 8                               26 - 5 - Concordo totalmente
 12                              26 - 5 - Concordo totalmente
 18                              26 - 5 - Concordo totalmente
 39                              26 - 5 - Concordo totalmente
 42                              26 - 5 - Concordo totalmente
 ...                                                      ...
 7178                            26 - 1 - Discordo totalmente
 7204                            26 - 1 - Discordo totalmente
 7215                            26 - 1 - Discordo totalmente
 7227                            26 - 1 - Discordo totalmente
 7240                            26 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Gosto de me sentir livre para fazer o que bem entender.
 Id_Agente
 14                              27 - 5 - Concordo totalmente
 28                              27 - 5 - Concordo totalmente
 97                              27 - 5 - Concordo totalmente
 105                             27 - 5 - Concordo totalmente
 136                             27 - 5 - Concordo totalmente
 ...                                                      ...
 7178                            27 - 1 - Discordo totalmente
 7180                            27 - 1 - Discordo totalmente
 7203                            27 - 1 - Discordo totalmente
 7223                            27 - 1 - Discordo totalmente
 7227                            27 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Gosto de trabalhar sozinho e independentemente.
 Id_Agente
 14                           28 - 5 - Concordo totalmente
 37                           28 - 5 - Concordo totalmente
 47                           28 - 5 - Concordo totalmente
 140                          28 - 5 - Concordo totalmente
 159                          28 - 5 - Concordo totalmente
 ...                                                   ...
 7195                         28 - 1 - Discordo totalmente
 7201                         28 - 1 - Discordo totalmente
 7223                         28 - 1 - Discordo totalmente
 7227                         28 - 1 - Discordo totalmente
 7239                         28 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Gosto de realizar tarefas melhor do que os outros.
 Id_Agente
 18                              29 - 5 - Concordo totalmente
 31                              29 - 5 - Concordo totalmente
 58                              29 - 5 - Concordo totalmente
 101                             29 - 5 - Concordo totalmente
 131                             29 - 5 - Concordo totalmente
 ...                                                      ...
 7195                            29 - 1 - Discordo totalmente
 7211                            29 - 1 - Discordo totalmente
 7216                            29 - 1 - Discordo totalmente
 7233                            29 - 1 - Discordo totalmente
 7238                            29 - 1 - Discordo totalmente

 [6556 rows x 1 columns],
           Gostaria de ser líder em qualquer emprego, profissão, área ou especialidade.
 Id_Agente
 6                               30 - 5 - Concordo totalmente

In [16]:
df_corrigido = pd.concat(data, axis=1)
df_corrigido.fillna('0 - Sem resposta', inplace=True)
df_corrigido.reset_index(drop=True, inplace=True)
df_corrigido

,Id_Agente,Cliente,Você está trabalhando no Campus ou em Casa?,Qual o tempo gasto no trajeto da sua residência até a empresa?,Qual a sua escolaridade?,Qual a sua área de estudo?,Você possui dependentes?,Quantos dependentes você possui?,Qual seu conhecimento em inglês?,Qual seu conhecimento em espanhol?,...,A maioria das pessoas precisam de algum tipo de apoio.,É bom trabalhar com meus colegas de trabalho.,Os melhores resultados vêm do trabalho em equipe.,Baseio meu trabalho em relações interpessoais.,Fico tenso quando estou trabalhando.,Providencio soluções para os meus problemas com rapidez.,Demonstro meu valor nas horas difíceis.,Falta de tempo não me assusta.,Pessoas fortes vêm de ambientes competitivos.,Gosto de ter um trabalho exigente.
0,1,Cliente 1,1 - Casa,0 - Sem resposta,3 - Ensino Superior incompleto,4 - Humanas,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Intermediário,...,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta
1,2,Cliente 2,1 - Casa,0 - Sem resposta,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Não tenho conhecimento em inglês,8 - Não tenho conhecimento em espanhol,...,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta
2,3,Cliente 2,1 - Casa,0 - Sem resposta,3 - Ensino Superior cursando,4 - Gestão de Pessoas/Negócios,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Não tenho conhecimento em espanhol,...,56 - 5 - Concordo totalmente,57 - 4 - Concordo,58 - 4 - Concordo,59 - 2 - Discordo,60 - 3 - Indiferente,61 - 3 - Indiferente,62 - 4 - Concordo,63 - 3 - Indiferente,64 - 4 - Concordo,65 - 2 - Discordo
3,4,Cliente 3,1 - Casa,0 - Sem resposta,3 - Ensino Superior concluído,4 - Saúde,5 - Não,0 - Sem resposta,7 - Básico,8 - Não tenho conhecimento em espanhol,...,56 - 4 - Concordo,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 4 - Concordo,61 - 4 - Concordo,62 - 4 - Concordo,63 - 3 - Indiferente,64 - 2 - Discordo,65 - 3 - Indiferente
4,5,Cliente 4,1 - Casa,0 - Sem resposta,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Avançado,8 - Básico,...,56 - 4 - Concordo,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 3 - Indiferente,61 - 4 - Concordo,62 - 4 - Concordo,63 - 4 - Concordo,64 - 3 - Indiferente,65 - 3 - Indiferente
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,7236,Cliente 6,1 - Campus,2 - Até 30min,3 - Ensino Superior cursando,4 - Humanas,5 - Não,0 - Sem resposta,7 - Fluente,8 - Não tenho conhecimento em espanhol,...,56 - 5 - Concordo totalmente,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 1 - Discordo totalmente,61 - 5 - Concordo totalmente,62 - 5 - Concordo totalmente,63 - 2 - Discordo,64 - 2 - Discordo,65 - 4 - Concordo
7236,7237,Cliente 6,1 - Campus,2 - Até 30min,3 - Ensino Médio completo,0 - Sem resposta,5 - Sim,6 - 3 ou mais,7 - Não tenho conhecimento em inglês,8 - Não tenho conhecimento em espanhol,...,56 - 4 - Concordo,57 - 5 - Concordo totalmente,58 - 5 - Concordo totalmente,59 - 3 - Indiferente,60 - 2 - Discordo,61 - 4 - Concordo,62 - 4 - Concordo,63 - 4 - Concordo,64 - 4 - Concordo,65 - 4 - Concordo
7237,7238,Cliente 17,1 - Campus,2 - De 1h à 1h30,3 - Ensino Superior cursando,4 - Exatas,5 - Não,0 - Sem resposta,7 - Básico,8 - Básico,...,56 - 4 - Concordo,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 2 - Discordo,61 - 4 - Concordo,62 - 3 - Indiferente,63 - 2 - Discordo,64 - 4 - Concordo,65 - 3 - Indiferente
7238,7239,Cliente 6,1 - Campus,2 - De 1h à 1h30,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Não tenho conhecimento em espanhol,...,56 - 5 - Concordo totalmente,57 - 5 - Concordo totalmente,58 - 5 - Concordo totalmente,59 - 1 - Discordo totalmente,60 - 2 - Discordo,61 - 4 - Concordo,62 - 4 - Concordo,63 - 4 - Concordo,64 - 4 - Concordo,65 - 4 - Concordo
7239,7240,Cliente 17,1 - Campus,2 - De 1h30 à 2h,3 - Ensino Superior concluído,4 - Gestão de Pessoas/Negócios,5 - Não,0 - Sem resposta,7 - Não tenho conhecimento em inglês,8 - Não tenho conhecimento em espanhol,...,56 - 5 - Concordo totalmente,57 - 5 - Concordo totalmente,58 - 5 - Concordo totalmente,59 - 2 - Discordo,60 - 2 - Discordo,61 - 4 - Concordo,62 - 5 - Concordo totalmente,63 - 2 - Discordo,64 - 4 - Concordo,65 - 4 - Concordo

## Verificação de dados duplicados

In [17]:
df_corrigido.duplicated().sum()

np.int64(0)

In [18]:
df_corrigido = df_corrigido.drop_duplicates()
df_corrigido.shape

(7240, 67)

## Adição dos dados de desempenho
Utilizaremos o Pandas Merge para unificar a base de questões e a base de desempenho.

In [19]:
df_completa = pd.merge(left=df_corrigido, 
                       right=df_desempenho, 
                       how='left', 
                       left_on='Id_Agente', right_on='Id_Agente')
df_completa

,Id_Agente,Cliente,Você está trabalhando no Campus ou em Casa?,Qual o tempo gasto no trajeto da sua residência até a empresa?,Qual a sua escolaridade?,Qual a sua área de estudo?,Você possui dependentes?,Quantos dependentes você possui?,Qual seu conhecimento em inglês?,Qual seu conhecimento em espanhol?,...,É bom trabalhar com meus colegas de trabalho.,Os melhores resultados vêm do trabalho em equipe.,Baseio meu trabalho em relações interpessoais.,Fico tenso quando estou trabalhando.,Providencio soluções para os meus problemas com rapidez.,Demonstro meu valor nas horas difíceis.,Falta de tempo não me assusta.,Pessoas fortes vêm de ambientes competitivos.,Gosto de ter um trabalho exigente.,Target
0,1,Cliente 1,1 - Casa,0 - Sem resposta,3 - Ensino Superior incompleto,4 - Humanas,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Intermediário,...,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,1
1,2,Cliente 2,1 - Casa,0 - Sem resposta,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Não tenho conhecimento em inglês,8 - Não tenho conhecimento em espanhol,...,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,0 - Sem resposta,1
2,3,Cliente 2,1 - Casa,0 - Sem resposta,3 - Ensino Superior cursando,4 - Gestão de Pessoas/Negócios,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Não tenho conhecimento em espanhol,...,57 - 4 - Concordo,58 - 4 - Concordo,59 - 2 - Discordo,60 - 3 - Indiferente,61 - 3 - Indiferente,62 - 4 - Concordo,63 - 3 - Indiferente,64 - 4 - Concordo,65 - 2 - Discordo,1
3,4,Cliente 3,1 - Casa,0 - Sem resposta,3 - Ensino Superior concluído,4 - Saúde,5 - Não,0 - Sem resposta,7 - Básico,8 - Não tenho conhecimento em espanhol,...,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 4 - Concordo,61 - 4 - Concordo,62 - 4 - Concordo,63 - 3 - Indiferente,64 - 2 - Discordo,65 - 3 - Indiferente,0
4,5,Cliente 4,1 - Casa,0 - Sem resposta,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Avançado,8 - Básico,...,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 3 - Indiferente,61 - 4 - Concordo,62 - 4 - Concordo,63 - 4 - Concordo,64 - 3 - Indiferente,65 - 3 - Indiferente,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7235,7236,Cliente 6,1 - Campus,2 - Até 30min,3 - Ensino Superior cursando,4 - Humanas,5 - Não,0 - Sem resposta,7 - Fluente,8 - Não tenho conhecimento em espanhol,...,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 1 - Discordo totalmente,61 - 5 - Concordo totalmente,62 - 5 - Concordo totalmente,63 - 2 - Discordo,64 - 2 - Discordo,65 - 4 - Concordo,1
7236,7237,Cliente 6,1 - Campus,2 - Até 30min,3 - Ensino Médio completo,0 - Sem resposta,5 - Sim,6 - 3 ou mais,7 - Não tenho conhecimento em inglês,8 - Não tenho conhecimento em espanhol,...,57 - 5 - Concordo totalmente,58 - 5 - Concordo totalmente,59 - 3 - Indiferente,60 - 2 - Discordo,61 - 4 - Concordo,62 - 4 - Concordo,63 - 4 - Concordo,64 - 4 - Concordo,65 - 4 - Concordo,1
7237,7238,Cliente 17,1 - Campus,2 - De 1h à 1h30,3 - Ensino Superior cursando,4 - Exatas,5 - Não,0 - Sem resposta,7 - Básico,8 - Básico,...,57 - 4 - Concordo,58 - 4 - Concordo,59 - 4 - Concordo,60 - 2 - Discordo,61 - 4 - Concordo,62 - 3 - Indiferente,63 - 2 - Discordo,64 - 4 - Concordo,65 - 3 - Indiferente,1
7238,7239,Cliente 6,1 - Campus,2 - De 1h à 1h30,3 - Ensino Médio completo,0 - Sem resposta,5 - Não,0 - Sem resposta,7 - Intermediário,8 - Não tenho conhecimento em espanhol,...,57 - 5 - Concordo totalmente,58 - 5 - Concordo totalmente,59 - 1 - Discordo totalmente,60 - 2 - Discordo,61 - 4 - Concordo,62 - 4 - Concordo,63 - 4 - Concordo,64 - 4 - Concordo,65 - 4 - Concordo,1
7239,7240,Cliente 17,1 - Campus,2 - De 1h30 à 2h,3 - Ensino Superior concluído,4 - Gestão de Pessoas/Negócios,5 - Não,0 - Sem resposta,7 - Não tenho conhecimento em inglês,8 - Não tenho conhecimento em espanhol,...,57 - 5 - Concordo totalmente,58 - 5 - Concordo totalmente,59 - 2 - Discordo,60 - 2 - Discordo,61 - 4 - Concordo,62 - 5 - Concordo totalmente,63 - 2 - Discordo,64 - 4 - Concordo,65 - 4 - Concordo,1

# Análise Exploratória dos Dados

## Utilizando o SweetViz

In [20]:
# Instale o pacote em seu ambiente virtual com "pip install sweetviz"
import sweetviz as sv

# Executa o Data Profiling
aed_sv = sv.analyze(df_completa, 
                    target_feat='Target')

# Salva o arquivo HTML final com o relatório
aed_sv.show_html('aed_sv.html')

ModuleNotFoundError: No module named 'sweetviz'

## Utilizando o Pandas Profiling

In [ ]:
# Instale o pacote em seu ambiente virtual com "pip install pandas_profiling".
import pandas_profiling

# Executa Data Profiling
aed_pp = df_completa.profile_report()

# Salva o arquivo HTML final com o relatório
aed_pp.to_file(output_file="aed_pp.html")

# Aplicação: Quais questões estão mais associadas ao bom desempenho dos agentes?
Identifique quais questões estão mais associadas ao bom desempenho dos agentes e explique como essa associação ocorre na base de dados.